### ISSUE TITLE
Extend Colly so pages with traditional error codes can be scraped

### ISSUE THREAD

**Issue by raylee** [gocolly/colly#104]
Most of the time Colly's logic in colly.go line 798 will be correct (if err == nil && response.StatusCode < 203). However, when trying to scrape sites which are either misconfigured or pages which are correctly giving error codes where the contents are interesting, Colly exits early.

I hit this on a real world site which is (I'm guessing) misconfigured. Google Chrome still renders the page contents even though the server is returning a 500 with the content. It would be useful if Colly could be used in these situations.

Example page in question:  https://aquicore.com/dictionary-posts/greenhouse-gas-emissions/

And on a separate topic, thanks for the useful tool!

**Comment by asciimoo** [comment]
@raylee I've added a `ParseHTTPErrorResponse` bool argument to `Collector`. You can parse `HTTP 500` responses by setting `c.ParseHTTPErrorResponse = true`.
