### ISSUE TITLE
onError context can be `nil`

### ISSUE THREAD

**Issue by tonybolzan** [gocolly/colly#105]
In some cases
`ctx` can be `nil` and cause segmentation fault  if used in `OnError` callback to get a value.
On my case, the error occurred in DNS resolution with custom transport
```go
c.OnError(func(r *colly.Response, err error) {
	value := r.Ctx.GetAny("foo")
})
``` 
File `colly.go:808` in `func handleOnError`

**Comment by asciimoo** [comment]
Thanks for the report. Could you verify that 9b3a02d solves the problem?

**Comment by tonybolzan** [comment]
Yes, worked like expected.
Thanks for the quick response.
