### ISSUE TITLE
google image scrap

### ISSUE THREAD

**Issue by TonyStark** [gocolly/colly#106]
Hello
I see instagram example, that is really good
however how to scrap/download google images from url?

**Comment by asciimoo** [comment]
Here is a python implementation of a google image scraper which contains the scraping logic of google images: https://github.com/asciimoo/searx/blob/master/searx/engines/google_images.py. It's pretty easy to reimplement it using Colly and its examples.
If you need further help in scraper implementations, check out our services: http://go-colly.org/services/
