### ISSUE TITLE
Use colly in a running context 

### ISSUE THREAD

**Issue by nicolasassi** [gocolly/colly#107]
Hi! I would like to know if and how can I apply colly in a backgound running context. Thanks!

**Comment by asciimoo** [comment]
@nicolasassi what is your exact use case? Collectors are thread safe, so you can use goroutines and standard go methods to achieve asynchronous behavior.

**Comment by nicolasassi** [comment]
Hi! I'm running chromedp for logging and scrapping pages as long as I couldn't achieve what I intended with Colly (I wanted to scrape LinkedIn pages, but I only get error pages and can't even logging) and chromedp initiates a new context.Context. I was curious them if I could use the opened context by chromedp (which is just a headless chrome instance) and headers and cookies for requests with Colly.

**Comment by asciimoo** [comment]
@nicolasassi colly has it's own [context](https://godoc.org/github.com/gocolly/colly#Context) which can be used to create a context for chromedp.

About the linkedin login: try to inspect the login network request with your browsers network inspector, and compare the request with your scrapers request. Fine tune the scraper if you see differences.

**Comment by araujobsd** [comment]
@nicolasassi Have you ever managed to make it work? I'm having the same doubt right now and got stuck with exactly the same thing.
