### ISSUE TITLE
AppEngine returns null from colly scraper

### ISSUE THREAD

**Issue by darkshuffle** [gocolly/colly#108]
I'm having a slight issue with app engine and wondering whether I've missed some config stage to get colly working correctly. Sorry if this is the wrong place to be posting this.

I created my code as a standalone API that takes an http request sends the params to the correct function which then instantiates the scrape. This works locally with no problems but after tweaking the build for AppEngine the scraper will only return null. I can hit other endpoints and see the endpoints being hit in the logs but with no return. The response from colly never seems to be created. I looked into the Colly AppEngine function but my router handles the requests the scraper itself never receives the request. Any ideas why this would function as a local server but not on appengine?

![local scrape result](https://user-images.githubusercontent.com/8877580/36783337-a0d64a92-1c73-11e8-8618-0efe4fafd650.png)
![appengine scrape result](https://user-images.githubusercontent.com/8877580/36783358-ac36bda4-1c73-11e8-8b54-8bda786b83f3.png)

![response being sent back to http caller not being instantiated](https://user-images.githubusercontent.com/8877580/36783684-c26dae56-1c74-11e8-9f90-ffe90cd670ac.png)

**Comment by asciimoo** [comment]
@darkshuffle you have to use https://godoc.org/github.com/gocolly/colly#Collector.Appengine to patch your collector to be able to perform network requests in AppEngine.

**Comment by darkshuffle** [comment]
Ok I thought so, and thanks for the speedy response, are there any examples of how to do this? I'm not quite sure where I should be calling Collector.Appengine as it expects an http.Request struct that I'm not currently passing to where the scraper is instantiated.

**Comment by asciimoo** [comment]
Here's an example in the pull request of this functionality: https://github.com/gocolly/colly/pull/49 . Extend `scrapeInstagramAccounts()` with a `*http.Request` parameter and you can pass `r` to your collector.

**Comment by darkshuffle** [comment]
Thanks, I just gave it a go passing r in and it seems to be functioning perfectly. Wasn't sure of the relevance of the Req but all sorted. Thanks again.
