### ISSUE TITLE
Stop to collecting data

### ISSUE THREAD

**Issue by dzakaammar** [gocolly/colly#109]
Sorry, I'm a newbie in Go and want to build a web scraper based on it. 
How did you do to stop the collecting process without exiting the application?  I couldn't find any related function or method in the doc. Thanks.

**Comment by asciimoo** [comment]
Colly stops if you don't perform further requests and the ongoing requests are finished.
It can be achieved multiple ways. It is done automatically, if you have fixed number of requests, or you can introduce a variable which indicates stop.

The following example stops the execution if an error occurs:

```go
c := colly.NewCollector()
stop := false

c.OnError(func(_ *colly.Response, _ error) {
    stop = true
})

for !stop {
    c.Visit("your url")
}
```

**Comment by saifat29** [comment]
I am using Async in Colly and want to stop my crawler after it satisfies a specific condition. I referred issue #26 and #109 but it is not working.

How to stop Colly running in Async mode?

**Comment by karust** [comment]
Another way to exit crawl is to call panic and recover 
```go
func CrawlSite(urlSite string, saveto string, config CollyConfig) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("exit crawl")
		}
	}()
        c := cly.NewCollector()

	// SOME CODE

	c.OnResponse(func(r *cly.Response) {
                // SOME CODE
		if (elapsed > waitTime) || (downloaded >= config.MaxAmount) {
			panic("Exit")
		}
                // SOME CODE
	})
        // SOME CODE
	c.Visit(url)
}
```
