### ISSUE TITLE
Set Initial URL to AllowURLRevisit

### ISSUE THREAD

**Issue by dzakaammar** [gocolly/colly#111]
I have a case when combining colly with a job scheduler. My case is  i want to set my initial url to be revisit every time the scraper running, and only that url that allowed. I've set redis storage on my scraper.

```
collector := colly.NewCollector()
collector.AllowURLRevisit = true
collector.Async = false

collector.OnRequest(func(r *colly.Request) {
 if collector.AllowURLRevisit {
  collector.AllowURLRevisit = false
 }
 log.Println("Visiting url : ", r.URL.String())
})

collector.Visit(url)
```
and when the collector begin to start, it always visiting the initial url twice. Is there any possible way to make it happen without duplicating data? Regards.

**Comment by asciimoo** [comment]
@dzakaammar try to use two collectors; one for the initial url with `AllowURLRevisit = true` and another for the rest of the pages with `AllowURLRevisit = false`. Thoughts?

**Comment by dzakaammar** [comment]
Oh that's right, i forgot that i could clone the collector. But even so, I have to do this

```
collector.OnRequest(func(r *colly.Request) {
 if collector.AllowURLRevisit {
  collector.AllowURLRevisit = false
 }
 log.Println("Visiting url : ", r.URL.String())
})
```

because i just want only the initial url to disallow to be revisited. Thanks.
