### ISSUE TITLE
Data cleaning, normalization and classification

### ISSUE THREAD

**Issue by alejoloaiza** [gocolly/colly#120]
Hi, should this framework also include tools for data cleaning, classification and normalization??? or do your recommend another framework for such things? thanks a lot.

**Comment by asciimoo** [comment]
@alejoloaiza could you tell me examples of data cleaning/normalization/classification methods that you would like to see in Colly? The purpose of Colly is to be a versatile and easy to use framework for scraping/crawling tasks, but if the desired methods are not closely related to scraping, I wouldn't extend `colly` package.

**Comment by alejoloaiza** [comment]
okay, I understand that,  maybe we can start extending a little the methods to extract the scraped data which are currently ChildText, Text, ..... maybe adding some additional logic to extract parts of the data based in regex or some basic conversions, like, if text is $60.000,00, scrapped value will be 60000, what do you think?

**Comment by asciimoo** [comment]
As I understand, these are general NLP/text processing methods. I think an independent package would be better for this, because it could be used in other projects, too. What do you think?

**Comment by alejoloaiza** [comment]
Okay, I was just thinking to extend the data extraction methods that you offer in order to be more selective, currently we are just extracting everything within tags (ChildText) or attribute (ChildAttr). Lets close this one if you agree.
