### ISSUE TITLE
Suggestion to have more control on collectors

### ISSUE THREAD

**Issue by alejoloaiza** [gocolly/colly#121]
Hello guys, thanks for this great scraper, I want to suggest some features to give more control into collectors (this is not an issue): 

1) In order to have more control in collectors I propose to have c.Stop() and c.Start() methods, this will help if by some reason we want to stop our scraping and later on continue in the point that we were. 
2) In practice in pages that are like search - results and then detail pages, it is common that you use two collectors, one to collect all the links to detail pages and another collector to visit the detail pages and scrap the information, sometimes we want our first collector to catch all detail links and after that we will start our scraping. Suggestion: To have a way to queue all links found by our first collector and start visiting them after I finish the collection. This can be done either with another method instead of Visit, like Queue(), or just by using the same Visit but having the collector in Stopped status (reference to point 1).

Thanks a lot. regards.

**Comment by asciimoo** [comment]
Thanks for the suggestions, I'm currently working on the second feature.

**Comment by llonchj** [comment]
@asciimoo are you also supporting pagination?

**Comment by asciimoo** [comment]
@llonchj pagination can be handled easily from an OnHTML callback. Google groups scraper contains a good example: https://github.com/gocolly/colly/blob/master/_examples/google_groups/google_groups.go#L51

```go
c.OnHTML("{next page link selector}", func(e *colly.HTMLElement) {
	e.Request.Visit(e.Attr("href"))
})
```

**Comment by llonchj** [comment]
thanks @asciimoo I am keen to test the Queue feature as I have already some use cases for.

**Comment by asciimoo** [comment]
I pushed the queue implementation (6d52331), you can find an example here: https://github.com/gocolly/colly/blob/master/_examples/queue/queue.go . Example with redis backend is coming soon.

**Comment by asciimoo** [comment]
http://go-colly.org/docs/examples/redis_backend/

**Comment by llonchj** [comment]
@asciimoo, I pass metadata using Context to the requests. Will make sense to queue a full request instead of the URL?

**Comment by asciimoo** [comment]
@llonchj good idea, it does make sense. We can replace `queue.Request` with `colly.Request` to keep the context and we can use `colly.Request` inside the `Queue` to perform requests.
I'm implementing the changes, thanks for the review.

**Comment by llonchj** [comment]
@asciimoo the change is even better to what i expected ;) you're amazing.

How can we use a priorityqueue? I can envision messages being pulled based on a particular sorting method? like link level, etc.. Will this be possible?

**Comment by llonchj** [comment]
I will assume queue.Request is correct, as interface for queue requests, but should include a colly.Request.

**Comment by asciimoo** [comment]
> I will assume queue.Request is correct, as interface for queue requests, but should include a colly.Request.

`queue.Request` is not necessary if we use `colly.Request`. `queue.Request` doesn't provide additional functionality.

> How can we use a priorityqueue?

The current queue doesn't handle priority, we have to implement it as another queue, I think.

**Comment by llonchj** [comment]
Yes, that will be the case if queue is an interface. do you plan to include
Context in queue.Request?

2018-04-14 19:00 GMT+10:00 Adam Tauber <notifications@github.com>:

**Comment by asciimoo** [comment]
I'm not sure if I understand how do you want to achieve the queue interface. Currently queue has a `Storage` interface, isn't it enough? We can extend the `queue.Storage` interface to support priority queue too and priority queue could be an independent implementation along with `queue.Queue`.

> Yes, that will be the case if queue is an interface. do you plan to include Context in queue.Request? 

Context is currently added by `colly.Request` if you use `queue.Queue.AddRequest()` with `colly.Request.New()`.

**Comment by llonchj** [comment]
@asciimoo you're right. thanks!

**Comment by alejoloaiza** [comment]
Thanks for the improvement, I will try it out!

**Comment by artemzi** [comment]
@asciimoo 
> pagination can be handled easily from an OnHTML callback. Google groups scraper contains a good example: 
does it have some restriction?  I use it as described but it follows `next` only a few times and stops.
