### ISSUE TITLE
[Question] Colly distributed scrapping ?

### ISSUE THREAD

**Issue by yspanchal** [gocolly/colly#122]
Hi,
According to [colly documentation](http://go-colly.org/docs/best_practices/distributed/#distributed-scrapers)  distributed scrapers
```
the best you can do is wrapping the scraper in a server. Server can be any kind of service like HTTP, TCP servers.
```
 Can anyone provide some more information and any examples.

**Comment by asciimoo** [comment]
@yspanchal check out http://go-colly.org/docs/examples/scraper_server/ or https://github.com/gocolly/colly/tree/master/_examples/scraper_server
