### ISSUE TITLE
How to store cookies for subsequent requests

### ISSUE THREAD

**Issue by darkshuffle** [gocolly/colly#126]
Apologies for posting here as not really an issue -
Due to apparent updates to their service, if you now follow the example for instagram scraping currently shown in the colly docs the scraper will only receive the first page of results with any subsequent visits returning status: Forbidden. I believe this is something to do with the cookies being set from the initial response (you can still click through to the next page json in browser). 
Is there an example or could the examples be updated to include a way to store the relevant cookie information for subsequent requests after the first visit. I've noticed there is a setCookies function in the docs but not sure how I can use it.

**Comment by asciimoo** [comment]
@darkshuffle cookie handling is automatic, so I'm not sure that this is the root cause of the bug. I'll check the scraper soon.

**Comment by darkshuffle** [comment]
Thanks, the data struct needs updating to include the graphql object that now contains the user object.

**Comment by asciimoo** [comment]
Yes and the URL is also changed, it requires a `query_hash` attribute which comes from https://www.instagram.com/static/bundles/base/Vendor.js/0b34a2e2f7c2.js .

**Comment by darkshuffle** [comment]
Interestingly, you can still copy the url with the query_id and reach the next page, but i expect that will probably be silently deprecated at some point.

**Comment by asciimoo** [comment]
Strange, it doesn't work with `query_id` for me.

**Comment by darkshuffle** [comment]
I now can't get anything to work at all, even copying the next page url directly from the site after load returns forbidden. Possible Instagram have just massively changed their security headers?

**Comment by matjazmav** [comment]
By default cookies are stored in memory, if you need to store them on a disk you can consider implementing Storage interface (https://github.com/gocolly/colly/blob/master/storage/storage.go#L30) like this:

```go
import (
	"fmt"
	"io/ioutil"
	"log"
	"net/url"

	"github.com/gocolly/colly/storage"
)

type DiskStorage struct {
	inMemoryStorage *storage.InMemoryStorage
}

// Init initializes the storage
func (ds *DiskStorage) Init() error {
	ds.inMemoryStorage = &storage.InMemoryStorage{}
	return ds.inMemoryStorage.Init()
}

// Visited receives and stores a request ID that is visited by the Collector
func (ds *DiskStorage) Visited(requestID uint64) error {
	return ds.inMemoryStorage.Visited(requestID)
}

// IsVisited returns true if the request was visited before IsVisited
// is called
func (ds *DiskStorage) IsVisited(requestID uint64) (bool, error) {
	return ds.inMemoryStorage.IsVisited(requestID)
}

// Cookies retrieves stored cookies for a given host
func (ds *DiskStorage) Cookies(u *url.URL) string {
	filePath := fmt.Sprintf(".cookies/%s", u.Hostname())
	buf, err := ioutil.ReadFile(filePath)
	if err != nil {
		return ""
	}
	return string(buf)
}

// SetCookies stores cookies for a given host
func (storage *DiskStorage) SetCookies(u *url.URL, cookies string) {
	filePath := fmt.Sprintf(".cookies/%s", u.Hostname())
	if err := ioutil.WriteFile(filePath, []byte(cookies), 0644); err != nil {
		log.Fatal(err)
	}
}

```

And then configure collector like this:

```go
c := colly.NewCollector()
c.SetStorage(&DiskStorage{})
```
