### ISSUE TITLE
Response.Save() only reads the first 10MB of a file

### ISSUE THREAD

**Issue by eagerhodgkin** [gocolly/colly#127]
Trying to save a file larger than 10MB using colly.Response.Save() only gets exactly 10MB of the file. Here is a program to demonstrate. Although it happens on any file regardless of the response headers.

```
package main

import (
        "fmt"
        "github.com/gocolly/colly"
)

func main() {
        c := colly.NewCollector()
        c.UserAgent = "Mozilla/5.0"
        c.SetRequestTimeout(0)

        c.OnResponse(func(r *colly.Response) {
                r.Save("file.bin")
        })

        c.Visit("http://speedtest.dallas.linode.com/100MB-dallas.bin")
}
```

**Comment by asciimoo** [comment]
@eagerhodgkin increase the `MaxBodySize` attribute of the collector (https://godoc.org/github.com/gocolly/colly#Collector).
