### ISSUE TITLE
Does Colly support colon-separated URL?

### ISSUE THREAD

**Issue by tomodian** [gocolly/colly#130]
Hi, thank you for building such a powerful library!

I was testing Colly with various websites and it seems colon separated URLs are sometimes ignored, especially on paginated URLs.

For example, given below URLs,

- `https://demo.com/pages`
- `https://demo.com/pages:1`
- `https://demo.com/pages:2`

The pages with `:*` is ignored.
It's quite unusual to see such URLs in 2018, but [Google encourages such URL](https://cloud.google.com/apis/design/custom_methods) and some web framework (well, CakePHP) uses the URL by default, so I would like to pinpoint either Colly doesn't support the URL by default, or my implementation is wrong.

It would be great to hear your thoughts 😄

**Comment by asciimoo** [comment]
It works for me with the following test code:

```go
package main

import (
    "log"

    "github.com/gocolly/colly"
)

func main() {
    c := colly.NewCollector()

    c.OnResponse(func(r *colly.Response) {
        log.Println("Got response:", r.Request.URL)
    })

    c.Visit("http://scooterlabs.com/echo/")
    c.Visit("http://scooterlabs.com/echo/:2")
    c.Visit("http://scooterlabs.com/echo/:3")
    c.Visit("http://scooterlabs.com/echo/:xyz")
}
```

Output:
```
2018/04/21 21:48:20 Got response: http://scooterlabs.com/echo/
2018/04/21 21:48:20 Got response: http://scooterlabs.com/echo/:2
2018/04/21 21:48:20 Got response: http://scooterlabs.com/echo/:3
2018/04/21 21:48:21 Got response: http://scooterlabs.com/echo/:xyz
```

**Comment by tomodian** [comment]
@asciimoo Thank you, the script is really helpful.
I will look into my code to see where is going wrong.
