### ISSUE TITLE
Use Golang standard Init function for storage interfaces

### ISSUE THREAD

**Issue by SimplySerenity** [gocolly/colly#137]
The current storage interface requires an Init function which I assume initially was for the purpose of error handling. Currently, however, the errors are ignored and it creates a less flexible design.

I'll use the [SQLite3 storage](https://github.com/velebak/colly-sqlite3-storage) as an example. It has a clear function which will drop the tables that are created for the storage. 

This would be handy but it can't really work with the current design. Attempting to clear before creating the collector means a nil pointer exception due to lack of Init. After creating the collector the problem becomes the tables need to be Init'd again. 

This example isn't the best because the problem could easily be worked around with a little bit of refactoring. (truncate instead of drop, and simply call it after creating the collector). That said I think this is still something that should be reflected upon.

I propose using the Golang standard Init to guarantee the storage is Init'd before any functions can operate on it, and a simple log.fatal in the case of error. Given I don't think unwinding the stack is necessary for something that would result in a panic anyway.

**Comment by asciimoo** [comment]
> The current storage interface requires an Init function which I assume initially was for the purpose of error handling

This is one reason, but there is another important one: You can use different storage instances in one script.

> Attempting to clear before creating the collector means a nil pointer exception due to lack of Init.

You can call `Init()` manually before `Clear()`.

> Given I don't think unwinding the stack is necessary for something that would result in a panic anyway.

Why would it result in a panic anyway?

**Comment by SimplySerenity** [comment]
> You can use different storage instances in one script. 

Oh right  :sweat_smile: I totally forgot about that detail. I think I'll just refactor the SQLite3 to be a little more friendly.

> Why would it result in a panic anyway?

Shouldn't it? If the storage fails to init the collector will try to access a nil pointer later anyway right?

**Comment by asciimoo** [comment]
> If the storage fails to initialize the collector will try to access a nil pointer later anyway right?

That's true but it can be avoided if we properly check the return value of `storage.Init()/collector.SetStorage()` functions.

**Comment by SimplySerenity** [comment]
I didn't realize the set storage function actually called `Init()` :sweat_smile: 

I'll read the source a bit more carefully before I open an issue next time. Thanks for your patience. :1st_place_medal:
