### ISSUE TITLE
Difference checking

### ISSUE THREAD

**Issue by gedw99** [gocolly/colly#140]
Quick question.

I need to scrape documentation from web sites. After I have grabbed the documentation from their web site I need to run jobs to go back everyday and only get anything new.

Do you have any functionality that handles this or will I need to write my own difference checking add on ?

Thanks alot for this project ! It looks great.

**Comment by gedw99** [comment]
it requires remembering from the past run and so is dependent on the
storage. So you right in that its not in scope for the project.

But i thought it was worth asking.

Might be best to close this ??

**Comment by vosmith** [comment]
I know this issue just closed, but perhaps an extension to the storage API could make sure hash of the page content similar to how the request ID is a hash of the URL.  It would work for the redis storage implementation I think. It would also bring about some more settings and checks in the collector for `pageUpdated` or something similar. 

Thoughts?

Thoughts
