### ISSUE TITLE
Web page interaction to get page

### ISSUE THREAD

**Issue by sathishvj** [gocolly/colly#144]
One of the sites I'm trying this on requires some data to be input and then a page is dynamically loaded.  However, the url remains exactly the same always.  

For example, one input field is a dropdown with a year in it, another input field is a text box with an index number that has to be input, then we click a button.  This loads the data on the page (with no change in url) and then I've to scrape the data.  

How can I do this with colly?

**Comment by asciimoo** [comment]
Probably the content is loaded by AJAX calls. Open your web debugger's (F12) network tab in your browser and check the requests.
Other possibility is that the site uses simple POST requests. You can check the page source to verify these theories.

Both scenarios are supported by Colly, you can perform AJAX calls and send POST requests.
