### ISSUE TITLE
Visit a local file?

### ISSUE THREAD

**Issue by sathishvj** [gocolly/colly#145]
I already have the html file downloaded. Is it possible to visit it as a local file?

**Comment by vosmith** [comment]
It seems like it's not impossible, but not supported out of the box.  Here is a thread about using a custom RoundTripper to implement the file:// protocol.

I don't have any personal experience with it.

https://github.com/golang/go/issues/2113

**Comment by asciimoo** [comment]
As a workaround, you can easily setup a static file server: https://gist.github.com/willurd/5720255

**Comment by Redorb** [comment]
This might be useful here: https://golang.org/src/net/http/filetransport.go Currently the std lib already has an implementation of RoundTripper for the file protocol.

**Comment by azbshiri** [comment]
@asciimoo We could change `(*Collector).scrape` to accept an `http.Client` or just overwrite `http.DefaultClient`

```
t := &http.Transport{}
t.RegisterProtocol("file", http.NewFileTransport(http.Dir("/")))
c := &http.Client{Transport: t}
collector.scrape(..., "GET", c)
```

```
t := &http.Transport{}
t.RegisterProtocol("file", http.NewFileTransport(http.Dir("/")))
c := &http.Client{Transport: t}
defaultClient = http.DefaultClient
http.DefaultClient = c
collector.scrape(..., "GET", ...)
http.DefaultClient = defaultClient
```

**Comment by asciimoo** [comment]
@vosmith you're right, it can be used to pass custom transport which can handle `file://` scheme.
