### ISSUE TITLE
add socks5 agnet

### ISSUE THREAD

**Issue by sunrisedo** [gocolly/colly#154]

**Comment by sunrisedo** [comment]
type Dial func(network, addr string) (net.Conn, error)
func (c *Collector) SetSocks5(d Dial) {
	t, ok := c.backend.Client.Transport.(*http.Transport)
	if c.backend.Client.Transport != nil && ok {
		t.Dial = d
	} else {
		c.backend.Client.Transport = &http.Transport{
			Dial: d,
		}
	}
}

**Comment by asciimoo** [comment]
It is possible to set socks proxy using `Collector.SetProxy("socks5://yourproxy.tld/")`: https://godoc.org/github.com/gocolly/colly#Collector.SetProxy
