### ISSUE TITLE
I can't login to evernote account.

### ISSUE THREAD

**Issue by davisjohndavis3** [gocolly/colly#156]
I am trying to login with Evernote account for scrapping some things. But I can't go through it. I used "username" and "password" titles for giving the credentials. Is this the right way ?. 

Thank you in advance.

     package main

    import (
	"log"
	"github.com/gocolly/colly"
     )

     func main() {
	     // create a new collector
	     c := colly.NewCollector()

	  // authenticate
	  err := c.Post("https://www.evernote.com/Login.action", map[string]string{"username": 
          "XXXXXX@XXX.com", "password": "*********"})
	  if err != nil {
		log.Fatal("Error : ",err)
	  }

        	// attach callbacks after login
	       c.OnResponse(func(r *colly.Response) {
	        	log.Println("response received", r.StatusCode)
	       })

        	// start scraping
	       c.Visit("https://www.evernote.com/")
       }

**Comment by asciimoo** [comment]
@davisjohndavis3 Post data names and values can be determined from the target site's source code.
In this case they have 4 items:
```
<input type="email" placeholder="Email" id="email" name="email" data-validate="email_required, email, email_in_use" >
<input type="password" placeholder="Password" id="password" name="password" data-validate="password_required" >
<input type="submit" id="contact-form-submit" class="button-primary" name="register">
<input type="hidden" name="_sourcePage" value="TRewqUBoP0TiMUD9T65RG_YvRLZ-1eYO3fqfqRu0fynRL_1nukNa4gH1t86pc1SP">
```

So you need to send `email`, `password` and `_sourcePage` as post variables.

**Comment by Honer08** [comment]
So it should look more like this?

```
// authenticate
  err := c.Post("https://www.evernote.com/Login.action", map[string]string{"email": 
      "XXXXXX@XXX.com", "password": "*********", "submit": "*********"}, "hidden": "TRewqUBoP0TiMUD9T65RG_YvRLZ-1eYO3fqfqRu0fynRL_1nukNa4gH1t86pc1SP")
```
