### ISSUE TITLE
Login is not working in  solve360

### ISSUE THREAD

**Issue by davisjohndavis3** [gocolly/colly#157]
I am not sure if this a correct way. I used loginname, password, csrf for login to solve360.   Do I need to pass any extra information? The "loginname" and "password" I got from the formdata ( By pressing F12).
Thanks in advance. Can you give me an example?

    package main

    import (
	"log"

	"github.com/gocolly/colly"
    )

    func main() {
	// create a new collector
	c := colly.NewCollector()

	// authenticate
	err := c.Post("https://secure.solve360.com/", map[string]string{"loginname": 
     "XXXXXXX@gmail.com", "password": "XXXX","csrf": "XXXXXXXXXXX"})
	if err != nil {
		log.Fatal(err)
	}

	// attach callbacks after login
	c.OnResponse(func(r *colly.Response) {
		log.Println("response received", string(r.Body))
	})

	// start scraping
	c.Visit("https://secure.solve360.com/")
     }

**Comment by asciimoo** [comment]
As I see they need a correct CSRF token too. You have to extract it from the site with an initial request.

**Comment by davisjohndavis3** [comment]
how to make an initial commit with colly

**Comment by asciimoo** [comment]
Simply call `c.Visit("https://solve360.com/")` before the post request and you need an `OnResponse`/`OnHTML` callback which extracts the CSRF token from the site.
