### ISSUE TITLE
Taking URL from Queue

### ISSUE THREAD

**Issue by rainbowhat** [gocolly/colly#162]
Would it be possible to be taking Jobs from Queue such as redis or other queues.

**Comment by asciimoo** [comment]
It is possible, see our redis queue implementation: https://github.com/gocolly/redisstorage .
We don't have a complete example with the redis queue, but we have one for redis in general and one for the queue:
- http://go-colly.org/docs/examples/queue/
- http://go-colly.org/docs/examples/redis_backend/
