### ISSUE TITLE
Processing OnResponse with Async

### ISSUE THREAD

**Issue by rainbowhat** [gocolly/colly#163]
When Async is true, the downloading is really fast despite having Delay & Parallelism 

It's so fast i can't download the files fast enough. At most a few files get downloaded
c.OnResponse(func(r *colly.Response) {
		output := fmt.Sprintf("%s", r.Request.URL)
		output2 := GetMD5Hash(output)
		r.Save(output2)
	})

If Asyc is false, increasing Parallelism doesn't seem to speed up the crawling , even without delay settings. 

Please advice how I could go about this.

**Comment by asciimoo** [comment]
Parallelism doesn't speed up crawling because it is just an attribute of the LimitRule, which *limits* the access to resources, and it doesn't parallelize your script. If you want to crawl with multiple threads, use https://godoc.org/github.com/gocolly/colly/queue or multiple goroutines.
