### ISSUE TITLE
High Count of Parallelism , Thread  causes failure

### ISSUE THREAD

**Issue by rainbowhat** [gocolly/colly#165]
1) How do i manage my Parallelism Count & Threads Count. I realise both has to be the same number to adjust the speed of request.

2) The purpose of this is to visit the url and download the html. I realise if i set say very high of 12 Parallelism with 12 Threads, it will fail to work, it will Spam On Request & download just only a few files. 1% of the urls files downloaded only. 

When i set it to say 6, it seems to work fine, files are downloading much more consistently with the request.

Any idea what is causing this? a Bug?

```
package main

import (
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/gocolly/colly"
	"github.com/gocolly/colly/queue"
)

func main() {
	url := "http://url.com/getJobTest"
	c := colly.NewCollector(
		colly.MaxDepth(1),
		colly.Async(false),
	)
	c.Limit(&colly.LimitRule{DomainGlob: "*domain.com", Parallelism: 6})

	q, _ := queue.New(
		6, // Number of consumer threads
		&queue.InMemoryQueueStorage{MaxSize: 100000}, // Use default queue storage
	)

	// On every a element which has href attribute call callback
	c.OnHTML("a[href]", func(e *colly.HTMLElement) {
		link := e.Attr("href")
		//Print link
		if strings.Contains(link, "/s/") {
			q.AddURL(link)
			fmt.Println("Add to Q :", link)
		}
	})

	c.OnResponse(func(r *colly.Response) {
		//fmt.Println("File Info", r.Request.URL)
		output := fmt.Sprintf("%s", r.Request.URL)
		output2 := GetMD5Hash(output)
		output3 := fmt.Sprintf("%s%s", output2, ".txt")
		r.Save(output3)
	})

	c.OnRequest(func(r *colly.Request) {
		fmt.Println("On Request :", r.URL)
	})
	q.AddURL(url)
	q.Run(c)

}

```

**Comment by asciimoo** [comment]
Could you paste the output of the `OnError` callback too?

**Comment by rainbowhat** [comment]
Hi,

It was returning Error 403 , Based on OnError callback. I believe that causes it not to download the page. 

Seems like i have to figure a way to integrate proxy into the equation. 

Thanks @asciimoo
