### ISSUE TITLE
Redis Storage , Crawl Url from External Input to Redis

### ISSUE THREAD

**Issue by rainbowhat** [gocolly/colly#167]
Data from Redis , inserted by Colly
"{\"URL\":\"https://www.link.com",\"Method\":\"GET\",\"Body\":null,\"ID\":0,\"Ctx\":{}}"

Generated from Other framework, inserted into Redis with same Prefix
"{\"URL\":\"https://www.link.com\",\"Method\":\"GET\",\"Body\":null,\"ID\":0,\"Ctx\":[]}"

By right it should be able to read this data from the queue but it's ignoring it , is it because it cant be done this way? 
I'm trying to do a insert of jobs from else where and colly just has to listen to the redis storage and retrieve the url to crawl. 

I already modified redisstorage to take the job from my redis. 

`
func main() {
	url := "http://link.com/getJobTest"

	
	c := colly.NewCollector(
		colly.MaxDepth(1),
		colly.Async(false),
	)
	c.AllowURLRevisit = false
	c.Limit(&colly.LimitRule{Parallelism: 2})

	storage := &redisstorage.Storage{
		Address:  "1234567:6379",
		Password: "xxx",
		DB:       0,
		Prefix:   "job01",
	}

	q, _ := queue.New(
		2,       // Number of consumer threads
		storage, // Number of consumer threads
	)

	c.OnResponse(func(r *colly.Response) {
		output := fmt.Sprintf("%s", r.Request.URL)
		output2 := GetMD5Hash(output)
		output3 := fmt.Sprintf("%s%s", output2, ".txt")
		r.Save(output3)
	})

	c.OnError(func(r *colly.Response, err error) {
		fmt.Println("On error :", err)
	})

	q.AddURL(url)
	// Consume URLs
	q.Run(c)

}`

`func (s *Storage) getQueueID() string {
	return fmt.Sprintf("%s", "job01")
}`

**Comment by rainbowhat** [comment]
I had to remove Ctx from a few files and that feels so wrong. Please advice how better can i handle this.

**Comment by Wangzhijie2016** [comment]
c.AllowURLRevisit = false
Modify to:
c.AllowURLRevisit = true

**Comment by Wangzhijie2016** [comment]
Why c.AllowURLRevisit = false ?  You inserted into redis with same URLs🤔

**Comment by rainbowhat** [comment]
@Wangzhijie2016 ,nope, i wont be inserting it with the same URL.
Basically I manage to get the code to listen to Redis and take jobs from Redis. But Inserting of jobs are coming from Laravel.

I had to remove CTX from GoColly because it wont accept my generated Empty Class for Variable CTX.

I'm looking for a better way to handle this because , this isnt very a right way to go about modifying GoColly, cant contribute back with my current method.

**Comment by asciimoo** [comment]
> But Inserting of jobs are coming from Laravel.

You can trigger the queue consumption (`queue.Run()`) periodically or when job arrives to redis.

> I had to remove CTX from GoColly because it wont accept my generated Empty Class for Variable CTX.

I don't fully understand the problem, could you explain it?

**Comment by rainbowhat** [comment]
@asciimoo 
I wanted to insert job outside of GO. 
Therefore i checked the Redis and retrieved the Job Format in Redis Value. 
It looks something like 
"{"URL":"https://www.link.com\",\"Method\":\"GET\",\"Body\":null,\"ID\":0,\"Ctx\":[]}"

Unfortunately , i'm unable to insert it and get it to work because CTX is i believe an empty object. 
I therefore modified gocolly and removed CTX and it started working.

I'm already inserting jobs to redis but just a modified version with CTX. That's quite a bad "hard coding" fix to my problem haha.

**Comment by asciimoo** [comment]
There is a difference between `"{"URL":"https://www.link.com",\"Method\":\"GET\",\"Body\":null,\"ID\":0,\"Ctx\":{}}"` and `"{"URL":"https://www.link.com\",\"Method\":\"GET\",\"Body\":null,\"ID\":0,\"Ctx\":[]}"`

The second tries to pass an empty array (`[]`) to `Ctx` while the first is an empty map (`{}`). Try to use `{}` instead of `[]`
