### ISSUE TITLE
Accessing Cookies

### ISSUE THREAD

**Issue by neshala** [gocolly/colly#168]
Hi,

I want to get cookies and attach them to request header as new param. How i can access cookies?
I make one request before this where i want to attach them, but have no idea how to get them.
So i want cookies to be sent here:

```
c.OnRequest(func(r *colly.Request) {
    r.Headers.Set("cookie", cookie)
})
```

Ideal would be to collect them here:

```
c.OnResponse(func(r *colly.Response) {
 // do some magic to get cookies
})
```

Thanks

**Comment by asciimoo** [comment]
You can use `Collector.Cookie()` to retrieve cookies: https://godoc.org/github.com/gocolly/colly#Collector.Cookies .
E.g.: `siteCookies := c.Cookies(r.Request.URL.String())`

**Comment by neshala** [comment]
Thanks, that solved my issue.

**Comment by manubidegain** [comment]
@asciimoo 
Hello, i can see on my login request the params : Username, Password, __RequestToken and AccessType (using the inspector in chrome at the login time)
When i use c.Post(web,map(values))
The web throws me a 500 error.
Can i show you my code if you want!
