### ISSUE TITLE
Limit on Proxy - Per IP Address

### ISSUE THREAD

**Issue by rainbowhat** [gocolly/colly#170]
It seems like with round robin , it can still accidentally overload one of the IP in terms of numbers of requests. 
9 Concurrent , 3 Proxy , I suspect one of the proxy is sending more than "3".

**Comment by asciimoo** [comment]
Could you provide a test that proves your theory?

**Comment by rainbowhat** [comment]
@asciimoo is there any code i could run to retrieve the proxy info , maybe OnRequest?

**Comment by rainbowhat** [comment]
@asciimoo  , did you test the proxy out? I launched 8 proxy and check the monitor after 12 hours. 
11Pm to 7AM - Proxy 1 
7AM onwards - Proxy 2 

I shutdown 6 of the 8 proxy while the code is running, it's still running fine meaning at any one time, only one proxy is being used, i've been trying to debug why i'm getting Forbidden Returns at Random. I think it's because the proxy isn't being properly used. 

Please advice how I could help you test this out / reproduce. Do you have telegram or something

**Comment by rainbowhat** [comment]
`

func main() {
	
	c := colly.NewCollector(
		colly.MaxDepth(1),
		colly.Async(false),
	)
	c.AllowURLRevisit = true
	c.Limit(&colly.LimitRule{Parallelism: 1,Delay: 5 * time.Second,})
	rp, err := proxy.RoundRobinProxySwitcher("http://123:55555", "http://456:55555", "http://789:55555", "http://11:55555", "http://22:55555", "http://33:55555", "http://23:55555", "http://123:55555")
	if err != nil {
		log.Fatal(err)
	}
	c.SetProxyFunc(rp)

	storage := &redisstorage.Storage{
		Address:  "redisIP:6379",
		Password: "123",
		DB:       0,
		Prefix:   "job02",
	}

	q, _ := queue.New(
		16,      // Number of consumer threads
		storage, // Number of consumer threads
	)

	c.OnResponse(func(r *colly.Response) {
		//Save File Code
		time.Sleep(2 * time.Second)
	})

	c.OnRequest(func(r *colly.Request) {
		fmt.Println("On Request :", r.URL)
	})

	c.OnError(func(r *colly.Response, err error) {
		fmt.Println("On error :", err)
	})

	q.Run(c)

}`

**Comment by asciimoo** [comment]
> Please advice how I could help you test this out / reproduce. Do you have telegram or something

We're on Freenode IRC, #colly channel.

> I shutdown 6 of the 8 proxy while the code is running, it's still running fine meaning at any one time, only one proxy is being used, i've been trying to debug why i'm getting Forbidden Returns at Random. I think it's because the proxy isn't being properly used.

Hmm.. This is strange.. The proxy switcher code is quite simple and it worked on my manual tests. I should write an automated test to check the functionality.

> 	c.Limit(&colly.LimitRule{Parallelism: 1,Delay: 5 * time.Second,})

This makes no sense with a 16 threaded queue. If you create a Limit rule without specifying the target domains, it will be applied to every request, so the parallelism of the queue won't have any effect.
