### ISSUE TITLE
Example using JSON POST?

### ISSUE THREAD

**Issue by expatmt** [gocolly/colly#175]
I am trying to scrape a page from a website that requires authentication first. The site processes logins using `POST` data and JSON payload. It appears that I need to use `func (*Collector) Request` and set the `accept` header first and then the request payload in JSON.

Are there any examples of how to craft this request? I've been stabbing at this for a few hours with no luck.

**Comment by asciimoo** [comment]
You can use `collector.PostRaw` (https://godoc.org/github.com/gocolly/colly#Collector.PostRaw) to send JSON. If you have to set additional headers, you can do it in a `collector.OnRequest` callback.

**Comment by expatmt** [comment]
Thanks for the help. For the benefit of anyone else in the same situation, I got it working with this:

```
payload := []byte(`{"user":{"email":"anon@example.com","password":"mypassword"}}`)
c := colly.NewCollector()
c.OnRequest(func(r *colly.Request) {
	r.Headers.Set("Content-Type", "application/json;charset=UTF-8")
})
err := c.PostRaw(URL, payload)
```

**Comment by mishop** [comment]
Regard, Can anyone convert me this working code to Colly. Thank you
`package main
 
import (
"fmt"
"net/http"
"strings"
"io/ioutil"
)
 
func main() {

url := "http://1024game.com/api"
payload := strings.NewReader(`term=4404094910003`)
req, _ := http.NewRequest("POST", url, payload)
req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
res, _ := http.DefaultClient.Do(req) 
defer res.Body.Close()

body, _ := ioutil.ReadAll(res.Body) 
fmt.Println(string(body))
}
`

**Comment by hookover** [comment]
but i can not get response.request.body data

**Comment by xiaokugua250** [comment]
> but i can not get response.request.body data

i get this problem too，have you solved this promblem？

**Comment by gabrielbergoc** [comment]
> but i can not get response.request.body data

it's not possible to get the body data after the request is sent; it's an io.Reader object, once read (when the request is sent), it cannot be read again.

**Comment by asciimoo** [comment]
You can add the request data to the context in the `OnRequest` callback and retrieve it from e.g. the `OnResponse` callback
