### ISSUE TITLE
Different URL but returning same data? view source in browser returning different data

### ISSUE THREAD

**Issue by sundirosun** [gocolly/colly#176]
Anyone have any ideas why colly response returning same data?
i checked view page source, it showed different data in browser

data i mean is on script window.pageData 

`https://www.lazada.sg/shop-mobiles/`
`✔ Final Sale for 64GB!! (Local 1 Year Warranty) Xiaomi Redmi 5 Plus, 64GB/ 4GB Ram or 32GB / 3GB RAM
Xiaomi Redmi 5A 16GB Dual-Sim`

`https://www.lazada.sg/shop-mobiles/?page=2`
`✔ Final Sale for 64GB!! (Local 1 Year Warranty) Xiaomi Redmi 5 Plus, 64GB/ 4GB Ram or 32GB / 3GB RAM
Xiaomi Redmi 5A 16GB Dual-Sim`

**Comment by asciimoo** [comment]
Could you paste the scraper's code?

**Comment by sundirosun** [comment]
i found out the problem, on request need to cookies
