### ISSUE TITLE
Warning/error message during installation

### ISSUE THREAD

**Issue by ndriyo** [gocolly/colly#177]
I have the following warning/error message when I tried to install colly using the following command go get -u github.com/gocolly/colly/...

package github.com/PuerkitoBio/goquery: no Go files in C:\Users\name\go\src\github.com\PuerkitoBio\goquery

Is there something missing from my side?

**Comment by asciimoo** [comment]
It works for me, what is your go version?

**Comment by ndriyo** [comment]
go version go1.10.3 windows/amd64

**Comment by ldesegur** [comment]
I had to go back to this package and do a git reset --hard on it. Then it worked.

**Comment by vosmith** [comment]
Closing as this seems to be more related to `go get` than colly.
