### ISSUE TITLE
about the CSS selector：ChildText

### ISSUE THREAD

**Issue by BeanWei** [gocolly/colly#181]
func (*HTMLElement) ChildText
func (h *HTMLElement) ChildText(goquerySelector string) string
ChildText returns the concatenated and stripped **text content of the matching** elements.

how can i  get the first  elements

eg:
`<div class="foo"><span>testone</span><span class="bar">testtwo</span></div>`

if i use the ChildText, i will get the  "testone testtwo ",but i only want to get the first the elements "testone", now i use the strings.Split to get it.
but, is there others way to solve it?
thx.

**Comment by vosmith** [comment]
Hmm can you use `.foo > span` as a selector?

**Comment by BeanWei** [comment]
@vosmith  , i had use it, but i can't get only the` testone`, ` .foo > span`  will get the  `"testonetesttwo "`, the ChildText will get the all ,not the first

**Comment by vosmith** [comment]
use `.foo > span:first-child` if you only want `testone`.  Let me know if it works!

**Comment by BeanWei** [comment]
@vosmith ， Wow，cool.
 `.foo > span:first-child`  this way is ok.
thank you so much! 👍

**Comment by krypticallusion** [comment]
```<div class="foo">testone<span class="bar">testtwo</span></div>```

What about this example? 


Sorry to barge in here after so much time has passed on from this issue.
