### ISSUE TITLE
Post Data Encoding?

### ISSUE THREAD

**Issue by CrazyMouse** [gocolly/colly#183]
why Post method need a map for form data and the key and value not encoding ?
e.g # not replace with %23

**Comment by vosmith** [comment]
@CrazyMouse I believe the map is very simple and flexible to work with.  It could be done with something like `url.Values` but even this is just a wrapper around a `map[string][]string`.  To be honest most people use the form values as a simple map so it simplifies things.

As for the value encoding, can you submit an example of it not working?  I have not found your issue to be the case.

**Comment by CrazyMouse** [comment]
Hi Smith，
 I am going sorry for the issue I submited 。after that I found It’is my web
server’s issue .
i hope you can understand my bad english

best wishes for you

Vincent Smith <notifications@github.com>于2018年7月13日 周五下午10:52写道：

**Comment by vosmith** [comment]
Lol no problem

你的英语不如我的中文差

(Google translate: "Your English is not as bad as my Chinese")
