### ISSUE TITLE
Should Collector.Clone() copy reference on WaitGroup or it should create new instance

### ISSUE THREAD

**Issue by gekpp** [gocolly/colly#184]
Hello.
My use case
I create one collector. Then I set it up with proxyFunc, User-Agent and other. I use this instance as a base collector for other collectors which I create using `Collector.Clone()`. If I have several clones and they work in sync mode then my program may likely panic on method Collector.Wait() with 

> panic: sync: WaitGroup is reused before previous Wait has returned
> 
> goroutine 64 [running]:
> sync.(*WaitGroup).Wait(0xc42034a830)
> 	/usr/local/Cellar/go/1.10.1/libexec/src/sync/waitgroup.go:131 +0xef
> github.com/gocolly/colly.(*Collector).Wait(0xc4200a6d00

I'm wondering if it is correct to copy reference to WaitGroup in Clone method. Should it be shared between original and cloned collectors?

**Comment by nange** [comment]
Now it is not be shared. see #182

**Comment by asciimoo** [comment]
Yup, hopefully #182 fixes this issue.
