### ISSUE TITLE
Not crawling multiple sites

### ISSUE THREAD

**Issue by jmvbxx** [gocolly/colly#192]
I'm trying to crawl several subdomains to see what `title` they return but my script is not hitting the `AllowedDomains`. I only get return on the first one.
```
func main() {
	c := colly.NewCollector(
		colly.AllowedDomains("1.domain.com", "2.domain.com"),
	)
	c.OnHTML("title", func(e *colly.HTMLElement) {
		link := e.Attr("title")
		fmt.Printf("Title: %q -> %s\n", e.Text, link)
		c.Visit(e.Request.AbsoluteURL(link))
	})
	c.OnRequest(func(r *colly.Request) {
		fmt.Println("Visiting", r.URL.String())
	})
	c.Visit("https://1.domain.com")
}
```
I can't use `c.Visit("https://domain.com")` because it redirects to a different domain.

Thanks so much in advance.

**Comment by jmvbxx** [comment]
Good morning .. I'd really like to implement gocolly into our solution soon. Any chance on someone looking at this issue?

Thanks!

**Comment by vosmith** [comment]
@jmvbxx, I'm trying to understand the structure of the sorry you are scraping.  So `title` element at `1.domain` has an attribute called `title` that has the value `2.domain`? Like this

`<title title="2.domain.com"> ... </title>`

**Comment by vosmith** [comment]
Ah, so something like
```
func main() {
	c := colly.NewCollector(
		colly.AllowedDomains("1.domain.com", "2.domain.com"),
	)
	c.OnHTML("title", func(e *colly.HTMLElement) {
		fmt.Printf("Title: %s\n", e.Text)
	})
	c.OnRequest(func(r *colly.Request) {
		fmt.Println("Visiting", r.URL.String())
	})
	c.Visit("https://1.domain.com")
        c.Visit("https://2.domain.com")
        c.Wait()
}
```

Is this close?  You can also use a `colly.Queue` to add your domains and process them sequentially.  Let me know if this works for you (tbh: I didn't actually run this)

**Comment by jmvbxx** [comment]
Ah ok.. I see. I thought c.Visit was only meant to have a single value. I
didn't realize the list would be repeated. Thanks for the insight. I'll
test now and try.

**Comment by jmvbxx** [comment]
Works like a charm! Your help is very much appreciated!
