### ISSUE TITLE
Download file from web with colly

### ISSUE THREAD

**Issue by schrodingerscat0224** [gocolly/colly#193]
Can I download files from HTTP with colly, please? If I can, how?

**Comment by vosmith** [comment]
Yes sir, if you use the `Collector.OnResponse()` callback, you will have access to the `Response.Body` variable.  It also has a nice `Response.Save()` method. Let me know if you need more information👍🏾

**Comment by slarsar** [comment]
Thank you

> Yes sir, if you use the `Collector.OnResponse()` callback, you will have access to the `Response.Body` variable. It also has a nice `Response.Save()` method. Let me know if you need more information👍🏾

Thank you

**Comment by aneesh-joshi** [comment]
@vosmith 
How can you access the name / path of the current response?
I'm looking for the argument to pass to the `r.Save()`

**Comment by WROIATE** [comment]
> How can you access the name / path of the current response?
> I'm looking for the argument to pass to the `r.Save()`

Use r.FileName()  will solve the question. And you also could use filepath.Ext() to get a ext and custom a file name for yourself, just like
```
filename := ""   //Costum for youself
dir := ""            // Download path
ext := filepath.Ext(r.Request.URL.String())
ceanExt := sanitize.BaseName(ext)
final_filename := dir + fmt.Sprintf("%s.%s", filename , cleanExt[1:])
// Finally, save it!
r.Save(final_filename)
```

**Comment by DylanLeeee** [comment]
I can use "colly.Save()" to save pictures, but when i want to save videos ,it doesn't work well. So i want to know how to save videos with "colly.Save()"

**Comment by coder054** [comment]
Work for me:
	c.OnResponse(func(r *colly.Response) {
		if strings.Contains(r.Headers.Get("Content-Type"), "video/mp4") {
			log.Println("dowloading")
			path := "./download/" + uuid.New().String() + ".mp4"
			err := r.Save(path)
			if err != nil {
				log.Println("dowload video error")
				log.Println(err)
				return
			}
			log.Println("dowloaded")
		}
	})

**Comment by intocowdin9** [comment]
> I can use "colly.Save()" to save pictures, but when i want to save videos ,it doesn't work well. So i want to know how to save videos with "colly.Save()"

now to save it bro. would u like show me the code

**Comment by MushiTheMoshi** [comment]
this is not working for me...

```.go
	cFile.OnHTML("script", func(e *colly.HTMLElement) {

                        *** removed for brevity ***
			if visited, _ := cDownload.HasVisited(FILE.(string)); !visited {
				log.Println("[!] visiting file", FILE)
				err = cDownload.Request("GET", FILE.(string), strings.NewReader(""), nil, nil)
				if err != nil {
					log.Fatal(err)
				}
				_ = e.Request.Visit(FILE.(string))
				log.Println("[!] visited file", FILE)
				cDownload.Wait()
			}
		}

	})

	cDownload.OnResponse(func(r *colly.Response) {
		for k, _ := range VIDEOS {
			r.Save("./downloads/" + k)  // File is downloaded but incomplete
		}
		log.Printf("[R] %#v", r.Headers)
	})
```

Any help is much appreciated

Regards,
Julio

**Comment by filefi** [comment]
> @vosmith How can you access the name / path of the current response? I'm looking for the argument to pass to the `r.Save()`

I found a solution:
```go
        c := colly.NewCollector(
		colly.UserAgent("myUserAgent"),
		colly.AllowedDomains("example.com"),
	)
	c2 := c.Clone()

	c.OnResponse(func(r *colly.Response) {
		// data items you scraped
		filename := "custom_name.html"
		url := "http://example.com/index.html"

		// Context provides a tiny layer for passing data between callbacks
		// Put stores a value of any type in Context
		r.Ctx.Put("filename", filename)
		r.Ctx.Put("url", url)

		// Use collector’s Request() function to be able to share context with other collectors.
		c2.Request("GET", url, nil, r.Ctx, nil)
	})

	c2.OnResponse(func(r *colly.Response) {
		// Get retrieves a string value from Context. Get returns an empty string if key not found
		filename := r.Ctx.Get("filename")
		url := r.Ctx.Get("url")
		fmt.Printf("filename:%s url:%s", filename, url)

		// now you can custom the path
		r.Save(filename)
	})

	c.Visit("http://example.com")
```

output:
```
$ go run .\main.go
filename:custom_name.html url:http://example.com/index.html
```
