### ISSUE TITLE
Second OnHTML callback is firing only at the end

### ISSUE THREAD

**Issue by kishorenc** [gocolly/colly#195]
I'm crawling a simple 10 page website like this:

```
c.OnHTML("a[href]", func(e *colly.HTMLElement) {
	link := e.Attr("href")
	c.Visit(e.Request.AbsoluteURL(link))
})

c.OnHTML("div#foo", func(e *colly.HTMLElement) {
	// index extracted content
	fmt.Printf("OnHTML called for %v\n", e.Request.URL.String())
})

c.OnRequest(func(r *colly.Request) {
	fmt.Println("Visiting", r.URL)
})

c.Visit(rootUrl)
```

The first `c.OnHTML("a[href]"` callback function is called promptly as the pages are fetched, but the second `c.OnHTML(site.contextSelector` callback is called for all pages at one go only when all the pages have been fetched.

**Comment by asciimoo** [comment]
This is the expected behavior, because you don't return from your first callback and the execution of the callbacks are sequential. The trivial fix is swapping the two functions, but you can use queue-s and async scraping too, to avoid this effect.
