### ISSUE TITLE
New project using colly

### ISSUE THREAD

**Issue by jesuiscamille** [gocolly/colly#199]
Hello ! I saw that you maintain a list of open-source projects which use colly on the `readme`. I've created a quote scrapper in golang, [goquotes](https://github.com/jesuiscamille/goquotes).

Feel free to add it :) ( or not )

EDIT: I forgot to mention that colly is really a project which improved my workflow a lot, so thanks to all of you :) !

**Comment by vosmith** [comment]
@jesuiscamille Glad colly has come in handy for you!  I think you should open up a PR and add your project to the `README`.
