### ISSUE TITLE
How to deal with compressed responses?

### ISSUE THREAD

**Issue by PedroVinicius** [gocolly/colly#204]
I need to extract content from a site whose responses are always sent compressed with Gzip, even if I don't ask for it. When colly visits the URL, it throws an error, as the content is not plain html. Is it possible to uncompress the response? If yes, how?

**Comment by asciimoo** [comment]
Currently Colly doesn't have built-in support for decompression. As a workaround, you can overwrite the original response body with a manually decompressed response body in an `OnResponse` callback:

```go
c.OnResponse(func(r *colly.Response) {
   // ...
   r.Body = decompressedBody
})
c.OnHTML(...)
```

**Comment by kataras** [comment]
@asciimoo @PedroVinicius there is an easy way that I crafted myself, maybe you can improve it for more decompression types, here you are @asciimoo you can copy-paste and adapt that code to the colly repo: https://github.com/Landoop/lenses-go/blob/master/client.go#L240-L381

**Comment by kataras** [comment]
aa don't forget to "Accept" the compression methods also: https://github.com/Landoop/lenses-go/blob/master/client.go#L183. If you need more help please just attach my name here

**Comment by asciimoo** [comment]
@kataras thanks for the solution. The standard HTTP lib has automatic decompression functionality, but in this case the webserver is misconfigured. It isn't clear me at first glance that your solution handles these edge cases or replaces the built-in decompression functionality.
Another solution is to add a `Decompress` function to `Response`, but it would be only a shortcut for the method I mentioned above.

**Comment by vosmith** [comment]
Closing as this seems to be an edge case that is more related to the target server not responding with proper headers.
