### ISSUE TITLE
How to perform breadth-first crawling instead of depth-first crawling?

### ISSUE THREAD

**Issue by hsluoyz** [gocolly/colly#209]
The official example performs depth-first crawling like recursion. Take the following website as an example. Main page ``0`` links to pages: ``1, 2``. Page ``1`` links to ``3, 4``. Page ``2`` links to ``5, 6``. The example will access the pages in order: ``0 -> 1 -> 3 -> 4 -> 2 -> 5 -> 6``.

A website with 7 pages:

```
       0
   1      2
 3  4    5  6
```

But I want my spider to crawl the pages in a breadth-first manner, aka the wanted access order would be: ``0 -> 1 -> 2 -> 3 -> 4 -> 5 -> 6``. Is there any way to do this? Thanks.

**Comment by asciimoo** [comment]
Use queues: https://godoc.org/github.com/gocolly/colly/queue . You can find an example here: http://go-colly.org/docs/examples/queue/ .
