### ISSUE TITLE
Random delay is not working as expected

### ISSUE THREAD

**Issue by gunsliver** [gocolly/colly#210]
Colly is awesome!
------------------------------------------------
Please forgive me if I am wrong as I am pretty new to go.
I assume that RandomDelay under LimitRule could be anything from nanosecond to second. 
I think that time.Duration is taking int64, Colly is giving it int instead. The conversion int(r.RandomDelay) will overflow when RandomDelay is going over 2 seconds. 
```go 
func (h *httpBackend) Do(request *http.Request, bodySize int) (*Response, error) {
        ...
	if r.RandomDelay != 0 {
		randomDelay = time.Duration(rand.Intn(int(r.RandomDelay)))
	}
	time.Sleep(r.Delay + randomDelay)
        ...
}
```

I would suggest changing it to int64:
``` go
randomDelay = time.Duration(rand.Int63n(int64(r.RandomDelay)))
```

Test:  https://play.golang.org/p/GyDE2uz_at2

**Comment by asciimoo** [comment]
You are right, `int`'s length is platform dependent, we should use `int64`. Thanks, fixed.
