### ISSUE TITLE
Is there a way to get the index of the current ``a[href]`` element?

### ISSUE THREAD

**Issue by hsluoyz** [gocolly/colly#211]
I want to know the index of the current ``a[href]`` element for the page, as follows.

```go
c.OnHTML("a[href]", func(e *colly.HTMLElement) {
	index := ...
	fmt.Println("This is %d-th hyperlink for this page", index)
})
```

Is there a way to do it? Thanks.

**Comment by asciimoo** [comment]
You can get it by calling `e.DOM.index()`

**Comment by hsluoyz** [comment]
It works. Thanks for the quick fix!
