### ISSUE TITLE
Is there context for a request?

### ISSUE THREAD

**Issue by hsluoyz** [gocolly/colly#213]
I'm writing a crawler that follows each ``<a href="xxx"></a>`` link of a page. I need to store a request-related information inside every request, because I need to read information from parent request. I know that ``Request.Ctx`` can store context information. But it seems to be a global space shared by all requests. If I store something into it via key like "info", a request can only read information from the previous (in the time) request, but not the parent request. I just want a request to read some data from its parent request.

See the following example:

```
[1] blog
  [2] /feed.html ---> can read request [1]'s context
    [3] /blog/* ---> can read request #2's context
    [3] /contact.html ---> can read request #2's context
  [2] /music ---> cannot read request #1's context, because it's covered by request #2's context.
```

**Comment by asciimoo** [comment]
Use `Request.Visit()` instead of `Collector.Visit()` to keep the previous request's context.

**Comment by hsluoyz** [comment]
What I used is ``Request.Visit()`` already, please see my code here: https://github.com/hsluoyz/logdance/blob/94aa78622b580c4ec14a4b5cd8bbae3ecf7d194e/main.go#L123-L128

If your previous request means request happened just before the current request, I know I can retrieve it via ``Request.Ctx``. But what I want is a request-specific context. So I can read request [1]'s context, also I can read request [2]'s context. These two contexts can be different.

Maybe this can be implemented by different keys in the current "global" context, like use request ID as key. But it doesn't have garbage collection: when a request (and its child requests) finishes, its key will not be automatically released. When crawling large number of pages, this memory can be very large.

So I still want to know if there is a request-specific context, which is for the request itself. And when the request (and its child requests) ends, its context can be released to save memory.

**Comment by asciimoo** [comment]
> So I still want to know if there is a request-specific context

Every context is request specific, there is no such "global context" in Colly, but you can inherit the parent request's context if you use `request.Visit` or create new contexts for every request using `collector.Visit`.

**Comment by hsluoyz** [comment]
You are right. I start with a root URL, and then use ``request.Visit()`` for all subsequent requests. So all requests share the first beginning context.

So I don't think I want to inherit the parent request's context, is there any way to do it?
