### ISSUE TITLE
Question about threads

### ISSUE THREAD

**Issue by dmakevic** [gocolly/colly#215]
I have one question about threading. Sorry for questioning but i don't know how to achieve this. Let's say i have list of hundred urls. I want to scrape each url from list in separate thread. Could i use a queue and set a number of consumer threads like this 
`number = 100 // set the number of urls in list
q, _ := queue.New(number, storage)
`
 Is it enough to achieve what i want. Also if i set parallelism to 2 does it limit number of requests to maximum 2 per DomainGlob.

Thank you in advance.

**Comment by asciimoo** [comment]
Yes, it does exactly what you wrote.

**Comment by rainbowhat** [comment]
Hi @asciimoo

Parallelism is for each thread? I believe per domain , but when it comes to thread what does it do , because I don't see it visiting different URL concurrently when using the queue example with c.Limit.

Is there anyway I could allow it to be visiting different domains concurrently ?
