### ISSUE TITLE
Preserve formatting in table cells

### ISSUE THREAD

**Issue by rkb2013** [gocolly/colly#217]
Hi - I'm trying to preserve the formatting `<br>` in table cells when I extract the contents of a `<td>` cell. 

What happens is if there are two lines of text (for e.g, an address) in the `<td>`, the code may look like:
`<td>` address line1`<br>1
address line2 `</td>`

When colly extracts this, I get the following:
address line1address line2 

with no spacing or line breaks since all the html has been stripped from the text. 

How can I work around / fix this so I receive readable text from the `<td>`

**Comment by vosmith** [comment]
Colly relies on [goquery](https://github.com/PuerkitoBio/goquery) for its HTML DOM parsing, which only supports the `.Text()` method to retrieve text information.  [This issue has been brought in goquery](https://github.com/PuerkitoBio/goquery/issues/242) , but it was determined to have too many edge cases to be worth it.

[This does happen in other libraries as well](https://stackoverflow.com/questions/37297282/keep-line-breaks-with-jquery-text-in-textarea) and the general solution is to take the HTML content of your cell and replace the `<br>` tags with `\n` characters.
