### ISSUE TITLE
Help Understanding Iteration

### ISSUE THREAD

**Issue by holmser** [gocolly/colly#218]
First, just wanted to say thank you for all the hard work that went into Colly.  I'm just getting started and I'm having trouble scraping a website with the following format:

```html
<h4>list 1</h4>
<ul>
    <li>a</li>
    <li>b</li>
</ul>

<h4>list 2</h4>
<ul>
    <li>a</li>
    <li>b</li>
</ul>
```

My goal is to have a struct that contains both the h4 data and the ul in a struct, but I can't figure out how to iterate through the site grabbing those chunks.  Thanks in advance for any help.

**Comment by asciimoo** [comment]
You can select the outter element in an `OnHTML` callback and the inner elements can be iterated with  https://godoc.org/github.com/gocolly/colly#HTMLElement.ForEach .
