### ISSUE TITLE
Lot's of http 0's

### ISSUE THREAD

**Issue by tamoyal** [gocolly/colly#219]
I've been trying to track errors from colly which I would think mostly amount to bad links. However, as soon as I started tracking via the `OnError` callback:

```
c.OnError(func(r *colly.Response, err error) {
		if r.StatusCode >= 400 || r.StatusCode < 200 {
			log.Printf("Bad link found <%d>: %s\n", r.StatusCode, r.Request.URL.String())
			bad_links = append(bad_links, r.Request.URL.String())
		}
	})
```

Now I see that a large % of requests return `Bad link found <0>:...` in the logs for all test sites I use. When I `curl` some at random, I get `200` every time and the response is fast so it shouldn't be a timeout issue. I've also considered there might be a blocking issue although my test sites are people's personal sites that should have close to no protection so I tried with a proxy gateway that requests from a different proxy on each request and got the same results - a large percentage of `Bad link found <0>:...`.

All of these errors are `net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

I will debug more but wanted to bring this up in case you had some idea of why this would happen. One of the test sites I am using is http://peaksmaker.com

**Comment by tamoyal** [comment]
Ok so a bit more information - all of these errors are `net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by asciimoo** [comment]
Do you have a test URL where I can reproduce the error?

**Comment by tamoyal** [comment]
@asciimoo Btw - I will try the limit rule soon and see if that helps.  Two URL's I have issues for:
http://peaksmaker.com
https://www.millcreekhtg.com/

I can probably give you 100 if you want 'em!

**Comment by tamoyal** [comment]
I confirmed the issue is the server
