### ISSUE TITLE
RSS Feed as Queue Source

### ISSUE THREAD

**Issue by vosmith** [gocolly/colly#220]
While working on an internal project, we were experimenting with search parameter on our target site.  We found that we could save this search as an RSS feed which would add new results as they become available.

Would anyone else find this as being useful to set up a `Queue` to pull the feed and scrape the links provided?

**Comment by asciimoo** [comment]
Parsing RSS is definitely a useful addition, but RSS can be parsed simply with OnXML callbacks afaik or not?

**Comment by vosmith** [comment]
Yeah you're right it can be done this way.  Setting up an `RssQueue` would just be more of a helper object.  In any case, it doesn't seem like many people are interested in it.

**Comment by vosmith** [comment]
closing due to lack of need/interest
