### ISSUE TITLE
Problem getting the data inside a noscript tag

### ISSUE THREAD

**Issue by MiguelCrespo** [gocolly/colly#221]
Hi, I am having a problem when I try to get the data inside a noscript tag. I am trying with this url https://stackoverflow.com/questions/20170275/how-to-find-a-type-of-an-object-in-go when I use the following code

```
c.OnHTML(`body`, func(e *colly.HTMLElement) {
			name = e.ChildAttr(`img`, "src")
			log.Println(fmt.Sprintf("Name: %s", name))
		})
```

It prints something but when I go inside a noscript tag

```
c.OnHTML(`body noscript`, func(e *colly.HTMLElement) {
			name = e.ChildAttr(`img`, "src")
			log.Println(fmt.Sprintf("Name: %s", name))
		})
```
_or `noscript`_

Nothing is printed even when the page actually have an image inside a noscript tag

```
<noscript>
  <div>
     <img src="/posts/20170275/ivc/06b4" class="dno" alt="" width="0" height="0">
  </div>
</noscript>
```

Any idea why is this happening?

**Comment by vosmith** [comment]
@MiguelCrespo I looked into this a little bit and found a trail that leads all the way back to the golang html package.

Colly relies on [goquery](https://github.com/PuerkioBio/goquery) for the DOM parsing where I [found this issue](https://github.com/PuerkitoBio/goquery/issues/139) mentioning the same problem you are having.  This issue references [An issue in Cascadia](https://github.com/PuerkitoBio/goquery/issues/139) which is the library used to compile CSS queries.  It seems to be the nature of the `net/html` parser, it converts the contents of a `noscript` tag into a text node, so nothing inside a noscript elem is searchable via CSS queries.

**Comment by MiguelCrespo** [comment]
Hi @vosmith thank you for your answer It pointed me in the right direction.
