### ISSUE TITLE
OnResponseHeader

### ISSUE THREAD

**Issue by zvodd** [gocolly/colly#228]
I ran into a problem where I am downloading a whole bunch of PDF files. It would be nice have a callback where I can parse the response headers before proceeding with the rest of the body and drop the request based on mime type.

I realize I could probably use the HEAD method as a work around, but some servers / web frameworks aren't always up to spec in supporting it properly.

So I think an on response header hook would be a great enhancement. I'm sure there would be more than a few use-cases outside my own for it.

**Comment by zvodd** [comment]
At the time of `OnRequest` the only thing I could attempt to use to filter is the URL, as the server's response headers letting me know the mime type are couldn't exist yet.
As with `OnResponse`; Yes it works, but the process has already downloaded the entire response (could be a huge file).
The ideal time to check would be after the response headers has been received, and before the body starts, I believe this is signaled by a double new line (after the last header field).

**Comment by vosmith** [comment]
Ah, [I see the problem now](https://github.com/gocolly/colly/blob/master/http_backend.go#L198).

The challenge here though is all of the callbacks are attached to the `Collector` and the response headers and body are captured in the `http_backend`.  Some adjustments would need to be made to change their interaction.

Or possibly expand the `LimitRule` to block content based on response headers?

@asciimoo what are your thoughts on this?

**Comment by zvodd** [comment]
https://github.com/gocolly/colly/blob/master/http_backend.go#L180
```
```

**Comment by zvodd** [comment]
I'm not sure how to approach this problem.
It certainly possible to read the HTTP Headers after L188 and before L198 (`ioutil.ReadAll(bodyReader)`), but hooking there would require a reference to the appropriate `colly.Collector` and I don't think that would be in line with the design of library/API.

There would need to be some reworking of `(c *Collector) fetch` and ` (*httpBackend).Cache` and of course `(h *httpBackend) Do` to make it fit.

I no expert on the library and the only solutions that come to my mind are undesirably hacky:
* `ioutil.ReadAll(bodyReader)` could be moved somewhere else... breaking the function up?
* a callback could be passed ALL the way into `*(h httpBackend) Do`.

Maybe someone with a better understanding could weigh in with some design proposition?
