### ISSUE TITLE
Referer extension : wrong header 

### ISSUE THREAD

**Issue by bmancone** [gocolly/colly#229]
In the Referer extension, the HTTP Header should be "Refe**r**er" instead of "Refe**rr**er".

(btw : https://en.wikipedia.org/wiki/HTTP_referer#Etymology)

**Comment by feelsad** [comment]
bmancone is right
why colly team have not conform this bug ?
it is already 3 months passed

**Comment by bmancone** [comment]
@JoeByte I guess because the tests failed in my PR : #230 

But the tests do not fail because of what I changed, but because of https://github.com/antchfx/xmlquery/issues/3 IMO.

Brice
