### ISSUE TITLE
Mocking Colly for Testing Purposes

### ISSUE THREAD

**Issue by limianwang** [gocolly/colly#236]
I am looking at how we would be able to mock the response body using go-colly such that I am able to run unit test to ensure that my web crawler operates in the expected way given a HTML body response. Is there an example somewhere I can refer to?

Thanks! (Awesome library btw.)

**Comment by vosmith** [comment]
@limianwang what I've seen done is to make a mock web server rather than mocking Colly itself.  You can see some examples of this in `colly_test.go`.

**Comment by limianwang** [comment]
@vosmith  Great! Thanks. I think that's a brilliant way.

**Comment by llonchj** [comment]
I built [knockttp](https://github.com/llonchj/knockttp) to mock http and create reproducible requests to test collectors.
