### ISSUE TITLE
JAVASCRIPT support

### ISSUE THREAD

**Issue by xperiafan13-rom** [gocolly/colly#247]
How i can wait for javascript generated DOM?

**Comment by Zaba505** [comment]
Hi @xperiafan13-rom 
Javascript generated DOMs require a javascript engine, as well as, an html and css renderer, which are the components a browser uses to display a javascript based website. Thus, without writing an entire browser in Go, your best bet is to use a headless browser such as: [Google Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome), [PhantomJS](http://phantomjs.org/), or [HtmlUnit](http://htmlunit.sourceforge.net/)
