### ISSUE TITLE
Post method with headers

### ISSUE THREAD

**Issue by mishop** [gocolly/colly#264]
Regard, Can anyone convert me this working code to Colly. Thank you

	package main
	 
	import (
		"fmt"
		"net/http"
		"strings"
		"io/ioutil"
	)
	 
	func main() {
		url := "http://1024game.org/api"
		payload := strings.NewReader(`term=4404094910003`)
		req, _ := http.NewRequest("POST", url, payload)
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		res, _ := http.DefaultClient.Do(req) 
		defer res.Body.Close()

		body, _ := ioutil.ReadAll(res.Body) 
		fmt.Println(string(body))
	}

**Comment by iPhosgen** [comment]
You can try something like this:

`package main

import (
	"net/http"
	"strings"

	"github.com/gocolly/colly"
)

func main() {
	c := colly.NewCollector()

	c.Request("POST",
		"http://1024game.org/api",
		strings.NewReader(`term=4404094910003`),
		nil,
		http.Header{"Content-Type": []string{"application/x-www-form-urlencoded"}}
	)
}`

**Comment by mishop** [comment]
Can you please write how to read response?
Thank you

**Comment by cute-angelia** [comment]
Can you please write how to read response?
Thank you
