### ISSUE TITLE
Support not storing certain URLs as visited in storage

### ISSUE THREAD

**Issue by zolamk** [gocolly/colly#270]
I think it would be useful to be able to ignore certain URLs when storing visited URLs.

For example on a paged listing page, the content might change but not the url and we may want to re-scrape the page.

We could pass the URL to the storages [IsVisited](https://github.com/gocolly/colly/blob/master/storage/storage.go#L70) method and let it handle it how ever.

**Comment by ermazi** [comment]
+1
