### ISSUE TITLE
how to pass Attr value to Colly for HTML decoding

### ISSUE THREAD

**Issue by kempeng** [gocolly/colly#272]
Hi,

I am new to Colly, but I like it!

I am trying to use it to scrape a particular HTML page that has a full html table stored as value of a <input> element. Using Colly, I can easily find the <input> element, but how do I pass the value information to Colly to analyse the table?

The html page conceptually contains this:
'\<input id="hiddentable" value="\<table\>\<tr\>\<td\>something\</td\>\</tr\>\</table\>"\>'

I was looking for something like:

var table string
c = colly.NewCollector()
	c.OnHTML("input[id=hiddentable]", func(e *colly.HTMLElement) {
		table := e.Attr("value")
        ct := c.Clone()
        **ct.ParseString(table)**
	})

**Comment by asciimoo** [comment]
First you have to create a goquery document: `goquery.NewDocumentFromReader(bytes.NewBuffer(htmlTable))`. Then you can use https://godoc.org/github.com/gocolly/colly#NewHTMLElementFromSelectionNode to create colly.HTMLElement objects from the parsed document.
Example: https://github.com/gocolly/colly/blob/master/colly.go#L946
