### ISSUE TITLE
Slow Request for simple query

### ISSUE THREAD

**Issue by pitw** [gocolly/colly#275]
I'm trying to scrape a simple JSON from a URL (is in code):

```
	coll := colly.NewCollector(colly.Debugger(&debug.LogDebugger{}))

	var body []byte
	coll.OnResponse(func(r *colly.Response) {
		body = r.Body
	})

	coll.Visit("https://www.alltron.ch/json/searchSuggestion?searchTerm=notebook")
        fmt.Println(string(body))

```

With colly I got about 8 Seconds until result. With a browser or using Postman it just needs about 300 ms.

What I'm doing wrong?

**Comment by asciimoo** [comment]
Do you use the same HTTP headers as Postman?

**Comment by pitw** [comment]
Yes. Problem seems to be that Colly runs in this specific case on Google App Engine which adds an additonal string to User-Agent Header: "AppEngine-Google; (+http://code.google.com/appengine; appid: APPID)"

Target is behind Akamai CDN and somehow they throttle request time if User-Agent Contains "AppEngine-Google"...

**Comment by LeMoussel** [comment]
Strange ....
See file [robots.txt](https://www.alltron.ch/robots.txt)

> User-agent: *
> Disallow: /

All User Agent are disallow !
