### ISSUE TITLE
Broken Colly with the latest commit on antchfx/htmlquery

### ISSUE THREAD

**Issue by teknokeras** [gocolly/colly#280]
About 6 hours ago Zhengchun remove FindEach from htmlquery in antchfx/htmlquery.
https://github.com/antchfx/htmlquery/commit/b8d36292614567671decfe6f96c7b8c432d3249b

FindEach is used in three places in colly, thus making errors when we run it:

/go/pkg/mod/github.com/gocolly/colly@v1.1.0/colly.go:972:4: undefined: htmlquery.FindEach
/go/pkg/mod/github.com/gocolly/colly@v1.1.0/xmlelement.go:137:3: undefined: htmlquery.FindEach
/go/pkg/mod/github.com/gocolly/colly@v1.1.0/xmlelement.go:161:3: undefined: htmlquery.FindEach

This is quite serious for new user who want to use Colly.

**Comment by peterhellberg** [comment]
This problem was just noticed by a user in the Gophers slack, current workaround is to use antchfx/htmlquery@db5c1236cbb43c58add1164a8b20d844683e537f

Should `FindEach` be implemented in Colly, or is there maybe replacement functionality in htmlquery that can be used?

**Comment by asciimoo** [comment]
Thanks for the info. A future proof solution would be a proper vendoring.

**Comment by jumbosushi** [comment]
Had the same issue. Solution from @epanov worked for me for now :+1:
