### ISSUE TITLE
Erro with FindEach() and FindEachWithBreak()

### ISSUE THREAD

**Issue by riquellopes** [gocolly/colly#285]
Hi everyone,

The methods it was removed of the current version of ```htmlquery```.  I sent a message to know if they'll replace for another.

(commit)[https://github.com/antchfx/htmlquery/commit/b8d36292614567671decfe6f96c7b8c432d3249b]

**Comment by asciimoo** [comment]
It is fixed in `1.2.0`.

**Comment by riquellopes** [comment]
thank u @asciimoo.
