### ISSUE TITLE
lib changed 

### ISSUE THREAD

**Issue by luanhailiang** [gocolly/colly#286]
../../gopath/pkg/mod/github.com/gocolly/colly@v1.1.0/colly.go:972:4: undefined: htmlquery.FindEach
../../gopath/pkg/mod/github.com/gocolly/colly@v1.1.0/xmlelement.go:137:3: undefined: htmlquery.FindEach
../../gopath/pkg/mod/github.com/gocolly/colly@v1.1.0/xmlelement.go:161:3: undefined: htmlquery.FindEach

![image](https://user-images.githubusercontent.com/1848784/52518796-8c740200-2c8b-11e9-93a1-3af86102bb92.png)

**Comment by riquellopes** [comment]
Hey @luanhailiang,

I solved this using the last commit ```db5c1236cbb43c58add1164a8b20d844683e537f```. U can try do that. But I'm using [dep](https://golang.github.io/dep/) to control my golang dependencies, it's simple. #285 

Best Regards

**Comment by PunkS7yle** [comment]
Still getting the errors using go mods + go get.

**Comment by asciimoo** [comment]
It is fixed in `1.2.0`.
