### ISSUE TITLE
Ability to pass Context to Visit method - Feature request

### ISSUE THREAD

**Issue by sabloger** [gocolly/colly#287]
Some times it is necessary to pass data from wherever call Visit to onResponse, onHtml callbacks, So the best way will be passing context to Visit method!

If there is any other way to do this, please let me know!

Thanks

**Comment by taosx** [comment]
You can pass context using the Request method on the collector.

`collector.Request(Metho, url, r, ctx, headers)`

**Comment by asciimoo** [comment]
Also, you can use `response.Request.Visit`  instead of `collector.Visit` which automatically passes the current context to the next request.
