### ISSUE TITLE
install package failed

### ISSUE THREAD

**Issue by iamMarkchu** [gocolly/colly#288]
``` bash
go get -u -v github.com/gocolly/colly/...
```
console output
➜  crawl go get -u -v github.com/gocolly/colly/...
github.com/gocolly/colly (download)
github.com/PuerkitoBio/goquery (download)
github.com/andybalholm/cascadia (download)
Fetching https://golang.org/x/net/html?go-get=1
https fetch failed: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/antchfx/htmlquery (download)
github.com/antchfx/xpath (download)
Fetching https://golang.org/x/net/html/charset?go-get=1
https fetch failed: Get https://golang.org/x/net/html/charset?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/net/html/charset: unrecognized import path "golang.org/x/net/html/charset" (https fetch: Get https://golang.org/x/net/html/charset?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/antchfx/xmlquery (download)
github.com/gobwas/glob (download)
github.com/kennygrant/sanitize (download)
github.com/saintfish/chardet (download)
github.com/temoto/robotstxt (download)
Fetching https://google.golang.org/appengine/urlfetch?go-get=1
https fetch failed: Get https://google.golang.org/appengine/urlfetch?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package google.golang.org/appengine/urlfetch: unrecognized import path "google.golang.org/appengine/urlfetch" (https fetch: Get https://google.golang.org/appengine/urlfetch?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/jawher/mow.cli (download)

**Comment by asciimoo** [comment]
Seems you have network issues: (`dial tcp 216.239.37.1:443: i/o timeout`).

**Comment by rajeshshegokar111** [comment]
what network issue is this

**Comment by rajeshshegokar111** [comment]
> Seems you have network issues: (`dial tcp 216.239.37.1:443: i/o timeout`).

how to solve this
