### ISSUE TITLE
It will not stop when I get the data I need in a request

### ISSUE THREAD

**Issue by liov** [gocolly/colly#289]
Colly stops if you don't perform further requests and the ongoing requests are finished.
It can be achieved multiple ways. It is done automatically, if you have fixed number of requests, or you can introduce a variable which indicates stop.

The following example stops the execution if an error occurs:

```go
c := colly.NewCollector()
stop := false

c.OnError(func(_ *colly.Response, _ error) {
    stop = true
})

for !stop {
    c.Visit("your url")
}
```

_Originally posted by @asciimoo in https://github.com/gocolly/colly/issues/109#issuecomment-369570532_

**Comment by asciimoo** [comment]
What is the question here?
