### ISSUE TITLE
Error: Too Many Requests and Client.Timeout exceeded while reading body

### ISSUE THREAD

**Issue by ztencmcp** [gocolly/colly#290]
I like Colly Project very much! Thank you guys!
here's issue i encounter almost every time i run my application:

"
[-]Request URL： https://github.com/search?o=desc&p=4&q=XYD%2BSMTP&s=indexed&type=Code 
[-]Error:  Too Many Requests
"

"
[-]request URL： https://github.com/search?o=desc&p=2&q=xyd%2Bmysql&s=indexed&type=Code 
[-]Error:  net/http: request canceled (Client.Timeout exceeded while reading body)
"

Is there any settings i missed or other resolutions? Any help  will appreciate. Thanks!

**Comment by asciimoo** [comment]
You are using more threads than the server allows. Reduce your parallelism if you scrape a single host.

**Comment by pjebs** [comment]
If Google detects you are scraping, Colly will produce the error: `Too Many Requests`.
Google returns a response with a recaptcha and http status code: 429
