### ISSUE TITLE
Specify the error

### ISSUE THREAD

**Issue by ll** [gocolly/colly#291]
The error that colly return are temporarily created, and there are inconvenient to specify what error it is.  

Although there have statusCodes, but the statusCode 0 represent many errors, such as timeout/redirect not allowed... so, the program is not sure what error occured. so, the error can't be treated correctly.

Can you specify the error just as **sql.ErrNoRows**? thanks a lot.

**Comment by asciimoo** [comment]
Colly uses different error types for different kind of errors (https://godoc.org/github.com/gocolly/colly#pkg-variables). Using these you can identify the error type.
