### ISSUE TITLE
How to set custom jar storage

### ISSUE THREAD

**Issue by letum** [gocolly/colly#300]
Hello! I would like to know how I can set a third party cookiejar? For example as you wrote in this configuration http://go-colly.org/docs/introduction/crawling/ 

Maybe it makes sense to change the type of input variable to interface `http.CookieJar` ?
```
func (c *Collector) SetCookieJar(j *cookiejar.Jar) {
	c.backend.Client.Jar = j
} 
```

**Comment by asciimoo** [comment]
Yes, you're right, it would be way more flexible. Could you work on this?
