### ISSUE TITLE
Does colly support incremental crawling?

### ISSUE THREAD

**Issue by hantmac** [gocolly/colly#304]
I have two questions:
- Does colly support incremental crawling?
- How does colly's distributed crawler accomplish the removal of duplicate URL requests?

Looking forward to your reply.Thanks!

**Comment by asciimoo** [comment]
Use a persistent storage backend like redis. This way both incremental crawling and distributed URL deduplication is possible if all the crawler instances are using the same storage backend.

example: http://go-colly.org/docs/examples/redis_backend/

**Comment by asciimoo** [comment]
Also, in most cases the network traffic is the bottleneck of a scraping job, so it's enough to distribute only the network part of the scraping, where a simple proxy rotation and some ssh tunnels can handle the load: http://go-colly.org/docs/examples/proxy_switcher/ .

**Comment by hantmac** [comment]
Thank you very much!
