### ISSUE TITLE
Scrape dynamic page

### ISSUE THREAD

**Issue by chenziliang** [gocolly/colly#308]
Some HTML elements in a page are created dynamically when the page are loaded fully in a browser like `document.createElement("figure")`. Is it possible to scrape this dynamically created elements by using Colly?

**Comment by jayhuang75** [comment]
For me, I use colly for the static web scraping, however, move to dynamic, I use chromedp.

**Comment by rainbowhat** [comment]
@chenziliang Looking into Puppeteer then Puppeteer cluster for dynamic page scrapping.

**Comment by chenziliang** [comment]
Thanks a lot @jayhuang75 @rainbowhat !

**Comment by chenziliang** [comment]
Is Colly targeting for dynamic web scrawling ?

**Comment by vosmith** [comment]
@chenziliang colly is not targeting dynamic pages at this time. :+1:

**Comment by mysticaltech** [comment]
Hey folks, FYI Ferret supports dynamic pages, https://github.com/MontFerret/ferret
