### ISSUE TITLE
c.Visit advice 

### ISSUE THREAD

**Issue by rainbowhat** [gocolly/colly#309]
// Set error handler
```
c.OnError(func(r *colly.Response, err error) {
	fmt.Println("Request URL:", r.Request.URL, "failed with response:", r, "\nError:", err)
})
```

If you guys face any issue, just us onError to debug

**Comment by rainbowhat** [comment]
file, err := os.Open("/path/to/file.txt")
    if err != nil {
        log.Fatal(err)
    }
    defer file.Close()

    scanner := bufio.NewScanner(file)
    for scanner.Scan() {
        fmt.Println(scanner.Text())
    }

    if err := scanner.Err(); err != nil {
        log.Fatal(err)
    }

Even when i read file and do a c.visit  it doesn't load

**Comment by vosmith** [comment]
I'm trying to replicate the behaviour that you are describing here, but I'm having a bit of trouble trying to understand.  Could you provide a complete example in a small project?

**Comment by rainbowhat** [comment]
// Execute the query
				rows, err := db.Query()
				if err != nil {
					panic(err.Error()) // proper error handling instead of panic in your app
				}

				// Get column names
				columns, err := rows.Columns()
				if err != nil {
					panic(err.Error()) // proper error handling instead of panic in your app
				}

				// Make a slice for the values
				values := make([]sql.RawBytes, len(columns))

				// rows.Scan wants '[]interface{}' as an argument, so we must copy the
				// references into such a slice
				// See http://code.google.com/p/go-wiki/wiki/InterfaceSlice for details
				scanArgs := make([]interface{}, len(values))
				for i := range values {
					scanArgs[i] = &values[i]
				}

				// Fetch rows
				for rows.Next() {
					// get RawBytes from data
					err = rows.Scan(scanArgs...)
					if err != nil {
						panic(err.Error()) // proper error handling instead of panic in your app
					}

					// Now do something with the data.
					// Here we just print each column as a string.
					var value string
					for i, col := range values {
						// Here we can check if the value is nil (NULL value)
						if col == nil {
							value = "NULL"
						} else {
							value = string(col)
						}
						fmt.Println(columns[i], ": ", value)
						c.Visit(fmt.Sprintf("%s", value))
					}
					fmt.Println("-----------------------------------")
				}
				if err = rows.Err(); err != nil {
					panic(err.Error()) // proper error handling instead of panic in your app
				}


c.Visit(fmt.Sprintf("%s", value)) wouldnt work, same concept as the text file
