### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by miandou** [gocolly/colly#316]
c.OnHTML("a[href]", func(e *colly.HTMLElement) {
		e.Request.Visit(e.Attr("href"))
	})

This recursion will cause memory overflow. It should be that the content crawled before has not been dropped by gc. How to solve this problem?

**Comment by miandou** [comment]
Maybe it's because a URL corresponds to too many html, and the parsing speed doesn't keep up with the crawling speed (using two C. OnHTML)?
Ps: crawl a web with less data, such as a video site, without memory overflow. But when crawling news websites, there will be memory overflow.
My English is very poor.Only relying on translation, sorry.

**Comment by nange** [comment]
Could you please add an example to reproduce it?

**Comment by miandou** [comment]
```
		// root is a url
		c := colly.NewCollector(
			func(c *colly.Collector) {
				c.AllowedDomains = []string{root}
			},
		)

		c.OnHTML("a[href]", func(e *colly.HTMLElement) {
			defer func() {
				if e := recover(); e != nil {
					fmt.Println(e)
				}
			}()

			req := e.Request
			href := e.Attr("href")
			e = nil    // gc？

			if !stop.off {    // stop.off := bool
				req.Visit(href)
			}
		})

		c.OnHTML("html", func(e *colly.HTMLElement) {
			defer func() {
				if e := recover(); e != nil {
					fmt.Println(e)
				}
			}()

			// handle result
			rs, err = DB.Exec("insert into info(taskId) values (?)", taskId)
			if err != nil {
				return
			}
			id, err := rs.LastInsertId()
			if err != nil {
				return
			}

			item := webInfo{}
			item.logType = int32(parChan.LogType)
			item.Channel = channel
			item.SecChannel = secChannel
			item.Url = e.Request.URL.String()
			item.Title = coverGBKToUTF8(e.DOM.Find("title").Text())
			text := coverGBKToUTF8(e.DOM.Find("p").Text())
			item.Summary = text
			item.Time = time.Now().Unix()
			currWoker := &idworker.IdWorker{}
			currWoker.InitIdWorker(1000, 1)
			item.Appid = id

			if client != nil {
				_ = client.SendWithPops(item.logType, item.Summary, item.Title, item.Appid, item.Channel, item.SecChannel, item.Url, taskId)
			}

		})
		c.Visit("http://" + root)

```

**Comment by nange** [comment]
@miandou 
In practice，you should use ``` colly.Async(true) ``` in most of case. And set the rate limit. eg:

```
var root = "your.domain.com" 
c := colly.NewCollector(
	colly.Async(true),
	colly.AllowedDomains(root),
        // colly.MaxDepth(10),  // set max depth if needed
)
c.Limit(&colly.LimitRule{
	DomainGlob:  "*",
	Parallelism: 1,
})

c.OnHTML("a[href]", func(e *colly.HTMLElement) {
	req := e.Request
	href := e.Attr("href")
	req.Visit(href)
})

c.Visit("http://" + root)
c.Wait()
fmt.Println("completed...")
```

**Comment by miandou** [comment]
@nange 
thanks，谢谢啦🙏

**Comment by nange** [comment]
.You are welcome. If it works, you can close the issue. 😃

**Comment by miandou** [comment]
It has been solved with the help of nange. I should read more source code to understand the principle.

**Comment by miandou** [comment]
@nange
I used Async and limit in your way. Although there was some improvement, memory was still rising slowly, from 10MB to 800MB and then fatal error. Is there no better way to limit crawling memory?

**Comment by nange** [comment]
@miandou 
maybe you crawl too much url, or you can try to decrease the MaxDepth.  Please add my wechat(id:nange880820) if you have further problem.

**Comment by mikefaraponov** [comment]
Why does not use queue instead of spawning goroutines recursively?

**Comment by mankeheaven** [comment]
queue use large memory, when I add 100,000,000 url, it crash @mikefaraponov

**Comment by asciimoo** [comment]
> queue use large memory, when I add 100,000,000 url, it crash @mikefaraponov

Add urls in smaller chunks. storing 100M url in the memory isn't a viable solution, or use a storage backend like redis or boltdb.

**Comment by mankeheaven** [comment]
@asciimoo thanks for your help
but I meet something with redis, it can only store 162280 url
![image](https://user-images.githubusercontent.com/17426397/76136336-5611dd80-606b-11ea-9cf2-71740bfc4884.png)
no error with redis, nor with colly
I set 2g memory with redis

**Comment by mankeheaven** [comment]
@asciimoo 
 sorry for trouble you
It's ok with colly to visit 100000000 urls
I did a mistake with our server, it calculates too low, and connecting counts too much

**Comment by asciimoo** [comment]
@mankeheaven no problem, thanks for the feedback.
