### ISSUE TITLE
Memory leaks by not closing http.Response.Body

### ISSUE THREAD

**Issue by adam-db** [gocolly/colly#321]
After running colly on very large scraping jobs I found that it gradually eats memory until it runs out of memory and crashes the process.

The leaks come from two places in the code:
 1. The Collector.checkRobots() function uses the httpBackend.Client directly but does not close the response body of the request.
 2. The httpBackend.Do() function leaves the defer call to res.Body.Close() too late so response bodies which error after being identified by headers as gzip compressed are not closed.

I have a small pull request to fix these issues.

**Comment by vinniyo** [comment]
Yo Adam. You ever get this fixed?

**Comment by adam-db** [comment]
Hi Vinniyo. These two problems were fixed in pull request #322 around the same time of this issue.
