### ISSUE TITLE
Why couldn't I download colly in China?

### ISSUE THREAD

**Issue by ascode** [gocolly/colly#325]
I executed 'go get -u github.com/gocolly/colly/...', but it always notice that:
```
https fetch: Get https://google.golang.org/appengine/urlfetch?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
```

**Comment by nange** [comment]
There's two methods to resolve the problem:
1. Use a proxy or VPN
2. If you use go1.11 and above, you can set the env var as below:
``` 
export GO111MODULE=on
export GOPROXY=https://goproxy.io
go get github.com/gocolly/colly

```

**Comment by axetroy** [comment]
or if you are using `Shadowsocks`
```bash
export http_proxy=http://0.0.0.0:1087;export https_proxy=http://0.0.0.0:1087;
go get github.com/gocolly/colly
```

**Comment by ascode** [comment]
Thank you all above!👌 I've get the package with your method.
