### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by damoncoo** [gocolly/colly#329]
Hi,
I'm using colly for my scraping tools, it is fantastic, but I'm struggling days of memory issue. 
Memory continue increasing util running out of it. I capture two images to show this.Please help me out of this.

```

```

![1556452976127](https://user-images.githubusercontent.com/4880373/56864247-ce8f2300-69f2-11e9-9394-221ecb8f4c00.jpg)
![FireShot Capture 005 - imovie-crawller inuse_space - localhost](https://user-images.githubusercontent.com/4880373/56864248-ce8f2300-69f2-11e9-83ae-90344a0aca45.png)

**Comment by MichaelMonashev** [comment]
I have the same problem:
![1](https://user-images.githubusercontent.com/6323434/57022508-063adc80-6c38-11e9-8230-26dd5c3a6f30.png)

**Comment by asciimoo** [comment]
Could you provide an example scraper?

**Comment by lightglitch** [comment]
@asciimoo just use your basic example with a site with a lot of pages like a store (try it with https://www.bybebe.pt/ for example), for me looks related to  the function handleOnHTML

**Comment by akacase** [comment]
I have a similar issue, let's take a simple Async collector via this code here:

```golang
		c := colly.NewCollector(
			colly.CacheDir(prefix+"/cache"),
			colly.IgnoreRobotsTxt(),
			colly.Async(true),
		)

		c.WithTransport(&http.Transport{
			DisableKeepAlives: true,
		})

		extensions.RandomUserAgent(c)

		c.SetRequestTimeout(time.Second * 10)
		c.AllowURLRevisit = false
```

Let's also constrain the crawler to the domain, so we can default to an infinite `MaxDepth`

```golang
		allowed := []*regexp.Regexp{}
		allowed = append(allowed, regexp.MustCompile(`.*salesforce.*`))
		c.URLFilters = allowed
```

This should constrain the crawler to only `.*salesforce.*` related domains, so we can crawl `https://salesforce.com`. I've tried `DomainGlob` as well and observed the same behavior. I'd like to count all the URLs on all pages I can find to do analysis afterwards, so I'll use this callback

```golang
		c.OnHTML("body", func(e *colly.HTMLElement) {
			s := make([]string, 0)

			e.ForEach("a[href]", func(_ int, e *colly.HTMLElement) {
				link := e.Attr("href")
				absolute := e.Request.AbsoluteURL(link)
				if url, err := url.ParseRequestURI(absolute); err == nil {
					if !strings.Contains(url.String(), ".jsp") &&
						!strings.Contains(url.String(), "tel:") &&
						!strings.Contains(url.String(), "javascript:") &&
						!strings.Contains(url.String(), "mailto:") &&
						!lookup.Has(hash) && url.String() != "" {
						s = append(s, url.String())
						e.Request.Visit(url.String())
					}
				}
			})
})
```

We seed the crawler and watch it balloon in memory usage

```golang
		if err := c.Visit("https://salesforce.com"); err != nil {
			log.Info().Err(err).Msg("couldn't visit url")
		}

		c.Wait()
```

You can see major negative effect of you're instantiating new crawlers per website, in my particular case, I either have a flat-file of URLs I'd like to crawl or I'm subscribed to a Pub/Sub of some sort and per iteration a new crawler is instantiated and waited upon, per iteration of this `for { }` memory isn't cleared at all, here's a pprof image to show the 7th iteration, this is with `nodefraction=0`:

![profile001](https://user-images.githubusercontent.com/5959454/61067826-7a32f700-a3d6-11e9-95c3-5170aeb9b13a.png)

This is with a 4 core box with about 32gbs of ram, it will kill the box before it can complete. I could be using this library incorrectly and please correct me if wrong, also thanks for all your hard work.

**Comment by lightglitch** [comment]
@akacase we solved our issue using the queue example http://go-colly.org/docs/examples/queue/, because it's not recursive the memory used is in control. You do loose the referral information because each link is open like a new window.

**Comment by akacase** [comment]
@lightglitch worried that was the case, thanks for the update. I'll rewrite, it's a shame golang doesn't support TCO.

**Comment by akacase** [comment]
> @akacase we solved our issue using the queue example http://go-colly.org/docs/examples/queue/, because it's not recursive the memory used is in control. You do loose the referral information because each link is open like a new window.

@lightglitch -- did you experience a major speed reduction by moving to the queuing model? speed has decreased at least by 10^1

**Comment by lightglitch** [comment]
@akacase for my use case we didn't do speed comparatives. That was something we didn't needed to take into account.

**Comment by lightglitch** [comment]
@akacase increasing the number of workers didn't helped?

**Comment by akacase** [comment]
> @akacase increasing the number of workers didn't helped?

It's somewhat noticeable, but nowhere near as performant as the recursive solution above. I've done `runtime.NumCPU()` and the latest thread count I've used is `32`, but it's still quite slow.

**Comment by znas-io** [comment]
@damoncoo if you're re-using a collector make sure you detach your OnHTML callback after you're done with it and attach a new one when needed.

`
querySelector := "div table tr td"
defer func() {
   collector.OnHTMLDetach(querySelector)
}()
collector.OnHTML(querySelector, func(e *colly.HTMLElement){
   fmt.Println(e.Text)
})
`

**Comment by lox** [comment]
I'm seeing exactly the same thing as the original issue, although I'm not using `OnHTML`, I'm using `OnResponse` and manually parsing with `goquery`. Surely this is a reasonably notable issue? Having to rewrite crawlers as queues is sometimes not possible.

**Comment by asciimoo** [comment]
Have you tried to use [queues](https://pkg.go.dev/github.com/gocolly/colly/v2@v2.1.0/queue?tab=doc)?

**Comment by lox** [comment]
@asciimoo 

> Having to rewrite crawlers as queues is sometimes not possible.

Yeah! It's really awkward though, as sometimes you don't know what urls you'll add before you begin the crawl (which makes it hard to use queues).

**Comment by asciimoo** [comment]
You can add urls to the queue dynamically, not just at the beginning of the scraping.

**Comment by asciimoo** [comment]
The only difference is that you call `queue.AddRequest` instead of `collector.Visit`.

**Comment by lox** [comment]
Hmmm, interesting, perhaps I am doing it wrong, does `queue.Run` block on the collector running each request? I was seeing my `AddRequest` calls not having an effect once the queue had emptied. If the first crawl is what populates subsequent url's in the queue, that is a problem.

**Comment by asciimoo** [comment]
`queue.Run` blocks while the queue has requests. If the queue is empty and you add new requests you have to call queue.Run again, but this shouldn't be the problem if you add new requests from your callbacks since it guarantees that there is at least one active request.

**Comment by asciimoo** [comment]
Take a look at the queue example: https://github.com/gocolly/colly/blob/master/_examples/queue/queue.go

**Comment by lox** [comment]
I'll take another look!

**Comment by lox** [comment]
Thanks @asciimoo, the key piece I was missing is that you need to `AddRequest` in `OnRequest`. That isn't mentioned in the http://go-colly.org/docs/examples/queue/ 🤔

Btw, this issue probably shouldn't be closed should it? There is absolutely unbounded memory usage in standard use of the Collector. This will bite anyone not using queues won't it?

**Comment by asciimoo** [comment]
> the key piece I was missing is that you need to AddRequest in OnRequest

It can be added in any callback.

> There is absolutely unbounded memory usage in standard use of the Collector

It only affects long running jobs. In these cases it's recommended to use queues.

**Comment by lox** [comment]
> It only affects long running jobs.

It's still an open issue though, isn't it? It should be fixable.

**Comment by akacase** [comment]
@lox should be fixable by eliminating the recursion or implementing some sort of trampoline. Go doesn't support TCO/TCE from a compiler optimization perspective, so it's up to us to unroll it, hence @asciimoo's suggestion to move to a queue, which is more iterative in nature; however they are most definitely slower and not as natural to use, since crawling is literally recursing a giant tree :)
