### ISSUE TITLE
When the set-cookie of response header is multiple, how get all of them

### ISSUE THREAD

**Issue by gcgxfqw** [gocolly/colly#335]
Set-Cookie: producte_run_to_dev_tomcat=; Max-Age=1; Expires=Thu, 16-May-2019 08:31:22 GMT; Path=/
Set-Cookie: JSESSIONID=8A12ACB1B1AD35E06C9F5A2291C06E81; Path=/; Secure; HttpOnly

**Comment by WGH-** [comment]
https://golang.org/pkg/net/http/#Header.Values
