### ISSUE TITLE
Can't override RedirectHandler after cloning collector

### ISSUE THREAD

**Issue by nicklaw5** [gocolly/colly#337]
I would like to be able override the RedirectHandler function after cloning a collector. This would look something like:

```go
c := colly.NewCollector()
c.RedirectHandler = func(req *http.Request, via []*http.Request) error {
    fmt.Println("This is the original RedirectHandler.")
    return nil
}

cloneCol := c.Clone()
cloneCol.RedirectHandler = func(req *http.Request, via []*http.Request) error {
    fmt.Println("This is the cloned RedirectHandler.")
    return nil
}
```

This doesn't appear possible at present. The cloned collector adheres to the original collector's RedirectHandler function.

Any suggestions?

**Comment by asciimoo** [comment]
Use `Collector.SetRedirectHander` which is new in colly v2.0.0.
