### ISSUE TITLE
GetProxy in proxy.go is not called on every request

### ISSUE THREAD

**Issue by dabba39** [gocolly/colly#339]
, DisableKeepAlives in Transport solves this problem. But there should be a more general solution i think?

**Comment by makelove** [comment]
same problem

I think it is a Big BUG of colly
unable to use proxy proxy freely

**Comment by asciimoo** [comment]
Could you provide code which reproduces the issue?

**Comment by IOsetting** [comment]
> Could you provide code which reproduces the issue?

I got this problem too, you can reproduce this issue exactly with the example http://go-colly.org/docs/examples/proxy_switcher/
GetProxy will be called only once so each time the same proxy will be used.

**Comment by superiss** [comment]
I got the same issue. with the rotating proxy. http://go-colly.org/docs/examples/proxy_switcher/

this for now helped.
https://github.com/gocolly/colly/issues/343#issuecomment-569526916

**Comment by wowinter13** [comment]
@asciimoo I think this issue could be closed

**Comment by asciimoo** [comment]
Thanks!
