### ISSUE TITLE
Add possibility to override Timeout value from Client

### ISSUE THREAD

**Issue by lucbarr** [gocolly/colly#348]
I stumbled upon this issue on a very time demanding request (around 13 seconds to complete): 
```
panic: Get <the url I requested>: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
This could be solved by changing the collector's backend default Client's timeout to a higher value (see [this line](https://github.com/gocolly/colly/blob/master/http_backend.go#L99), hard setting the Timeout value to 10 seconds), but...

As defined [here](https://github.com/gocolly/colly/blob/master/colly.go#L242-L254), a way to configure a collector is by passing a `func (*Collector)` at `NewCollector(options ...func(*Collector)` calls. By doing that there is no way to override a collector's `httpBackend`'s `Client`, [since it is private](https://github.com/gocolly/colly/blob/master/colly.go#L119). You can set a custom `http.RoundTripper` with `WithTransport(transport http.RoundTripper)`, but you can't change the `Timeout` value.

Is there a reason to not allow a collector to use a non-default `http.Client`, or more specifically a custom `Client.Timeout` value ? If not, I could gladly issue a PR on this (:

**Comment by asciimoo** [comment]
What is the problem with https://godoc.org/github.com/gocolly/colly#Collector.SetRequestTimeout?
