### ISSUE TITLE
Get css attribute that is not in-line

### ISSUE THREAD

**Issue by rafa-acioly** [gocolly/colly#353]
i'm crawling this site and some information are rendered using a background-image along with background-position, i've already got the image that are being used but now i need to get this background-position information, it's posible to get this information when it's not in-line (using style tag)

Page html example:

```html
<div class="bg-img random-class"><!-- nothing here --></div>
```

```cs
.bg-img { background-image: url("") ;}

// shows a single number inside the image
.random-class { background-position: -100px -100px; } 
```

This `random-class` is a sequence of 5 caracters that shows up randomically, i've already got 2 classes that show the same number, for that reason i cannot trust the "random-class"

**Comment by asciimoo** [comment]
Currently colly cannot parse css, try to use https://github.com/aymerick/douceur to parse `<style>` tags
