### ISSUE TITLE
Proposal. Precompile selectors such as base[href] using cascadia

### ISSUE THREAD

**Issue by moredure** [gocolly/colly#354]
goquery has support for precompiled matchers using cascadia. FindMatcher, ClosestMatcher, FilterMatcher, etc.

**Comment by mikefaraponov** [comment]
It should increase performance a little bit

**Comment by asciimoo** [comment]
Do you have exact numbers on the performance improvement?

**Comment by mikefaraponov** [comment]
goos: darwin
goarch: amd64
pkg: labs.internetvikings.com/polarbear/fastcrawler/app/services/parser
BenchmarkCascadia_Compile/parse-4         	 3000000	       370 ns/op	      96 B/op	       3 allocs/op

it's benchmark for cascadia compile function, so overall performance should increase on this amount. As I understand number of operations required to find element on the page should decrease for 370 ns/op and a little bit allocations also decreased. Not significant, but also not requires complex refactoring

**Comment by mikefaraponov** [comment]
goos: darwin
goarch: amd64
BenchmarkCompile_Compile/compile-4         	 3000000	       370 ns/op	      96 B/op	       3 allocs/op
PASS
