### ISSUE TITLE
use RoundRobinProxySwitcher But Sometimes the colly.Request.ProxyURL is empty.

### ISSUE THREAD

**Issue by zplzpl** [gocolly/colly#366]
use RoundRobinProxySwitcher But Sometimes the colly.Request.ProxyURL is empty.

NOTE: not use CacheDir
Sometimes the requested proxy is empty, not every request.

I don't think it's a problem with RoundRobinProxySwitcher.

**Comment by zplzpl** [comment]
#339

**Comment by zplzpl** [comment]
I found the exact reason

**Comment by Poincare2013** [comment]
what's the reason? r.ProxyURL is always empty

**Comment by afunnydev** [comment]
Same here, the ProxyURL is always empty. Is this expected behavior?

**Comment by liveangela** [comment]
same problem. really appreciate for the solution @zplzpl

**Comment by denisdubovitskiy** [comment]
Still having issues with this. Ctx on request is always empty
