### ISSUE TITLE
Suggestion: Sherlock example

### ISSUE THREAD

**Issue by lucmski** [gocolly/colly#372]
Hi guys,

Hope you are all well !

I was wondering how to enqueue urls to check and get custom rules after the response is received.

Example:
https://github.com/sherlock-project/sherlock/blob/master/data.json

The idea is to have a sherlock clone with gocolly. **Is it possible ?**

Cheers,
L

**Comment by asciimoo** [comment]
@lucmski it is absolutely possible, you just need an onResponse and onError callback where you can check the result of the requests.
