### ISSUE TITLE
Problem Saving a large file using Response.Save

### ISSUE THREAD

**Issue by cbolgiano** [gocolly/colly#374]
Using go-colly how does one download a zip that is more than 20mb in size?  I use the Save function to save the body of the response with no problem when the body is <= 10.5mb.  I have tried to set the MaxBodySize to 0 in efforts to avoid the default limit but still no luck.  Based on the documentation that allows the response to be of any size.

**Comment by liguoqinjim** [comment]
```go
col := colly.NewCollector(colly.MaxBodySize(100 * 1024 * 1024))
```
This can download file <= 100mb😃

**Comment by asciimoo** [comment]
Thanks for the answer @liguoqinjim
