### ISSUE TITLE
Save data to file

### ISSUE THREAD

**Issue by wangxiaodiao** [gocolly/colly#394]
panic: runtime error: slice bounds out of range [:4097] with capacity 4096

goroutine 60 [running]:
bufio.(*Writer).Flush(0xc000080040, 0xc002e3cac0, 0x1)
        /usr/local/go/src/bufio/bufio.go:593 +0x1c0
bufio.(*Writer).WriteString(0xc000080040, 0xc002e3cac0, 0x2f, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:696 +0x42
encoding/csv.(*Writer).Write(0xc000178000, 0xc000630c90, 0x4, 0x4, 0x13, 0xc002e2f660)
        /usr/local/go/src/encoding/csv/writer.go:63 +0x46d
main.main.func4(0xc002dedf80)

**Comment by vosmith** [comment]
Looks like you are writing something to a CSV file, but you have run out of space in your buffer. I don't think this is an issue with Colly
