### ISSUE TITLE
Why does visiting facebook return a garbled code

### ISSUE THREAD

**Issue by zzsure** [gocolly/colly#395]
`func crawl(url, lang string) (string, error) {
    c := colly.NewCollector()
	extensions.RandomUserAgent(c)
	extensions.Referer(c)
	c.OnRequest(func(r *colly.Request) {
		//r.Headers.Set("Host", "facebook.com")
        r.Headers.Set("Connection", "keep-alive")
        r.Headers.Set("Accept", "*/*")
        //r.Headers.Set("Origin", "http://facebook.com")
        r.Headers.Set("Accept-Encoding", "gzip, deflate, br")
        r.Headers.Set("Accept-Language", "zh-CN,zh;q=0.9;en-US,en;q=0.8")
		r.Headers.Set("Content-Type", "text/html")
		r.ResponseCharacterEncoding = "utf-8"
	})

    var ret string
    var err error

    c.OnResponse(func(resp *colly.Response) {
    	fmt.Println(string(resp.Body))
    })

	c.OnError(func(resp *colly.Response, errHttp error) {
        err = errHttp
    })

    err = c.Visit(url)

    return ret, err
}`

**Comment by zzsure** [comment]
$��Vq��"�<9�$�&����@�r�Ӵ�o�כ���s�%��<   ��;����iZ�B��n�t#B��iF��Jǂ�R�                                                                                              �E
C�d(F3�K�nU�{��B�g�"S���'.Z��*�4��ef7^���z����[���D8�   �"�1���T�u�U����`g�\%�4R�x��@'Q��/ii2���T���v��!��eċ��t6^a|0���rN^��2��q��Ȍ�6�<�v�7m~+j�����+B�.[*R�IT��kh��C
                                                                                                                                                                f��Х
                                                                                                                                                                    'I~W��'�-��LX~�l(��ʔ$B�Z�3�<�$ <U8*��MPL�z�)-��$�q���6D}hC�O�&���l
w��ź�y��ú[%�7l��-e��@w�6N��&$"�#��9��c�����0����(y�7�L�S�)O���7B��]�}���������ڝʌ�2��-%<�HΏJ�3;��h:�t�kl��@�)�W�k�n��iS�P�3y��~��
                                                                                                                                %[�H XZJ Q��D��P?���FC#����ŉ�:#���5қ��4�TԿz7�U�\c�ބ��.[��Jq�h��/��0    蜫���A�B��f���i�0��d
                                                                                                                                                                                                                            ���\O_     �]Dw
gy��I   C�D�]�G�R�R6j��+6�c[
                            �=�4}�oO����
                                         �3Æ����C-&�=�G��C؈�l.��W�_��z��h��Dj�D�X���@���cSM���Xj��BϬ0�`-���t�Ľ
                                                                                                              �ʾM1!ڷ0)-)��$�G�+Y55D�g�R1δ>�E�-Y����UF�if�k����Y���C3��u]q��%fL���؜�|��+�$�{�5�6�����R����ƌs�s��">�O9L5�?0�

**Comment by vosmith** [comment]
Looks like it's gzipped. I would remove the gzip option from your Accept Encoding header. Or you will have to decompress it yourself using the compress/gzip library

**Comment by eaglexiang** [comment]
> Accept-Encoding

try to remove `br` from your `Accept-Encoding`
