### ISSUE TITLE
Onhtml character problem

### ISSUE THREAD

**Issue by gouki777** [gocolly/colly#400]
hi
i want to  get info-title name,but  character set problems lead to garbled code.  
Please tell me what should I do?  
htlm head used gb2312,but info-title use UTF-8.  
What's  way to parse this character in colly  
```
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
  <title>《女超人第五季》</title>
...........................
    <div class="info-title">
     <h1>女超人第五季</h1>(2019)
    </div>
```
my colly used r.ResponseCharacterEncoding = utf-8 , but no good.
<pre>
	c.OnRequest(func(r *colly.Request) {
		r.Headers.Set("Connection", "keep-alive")
		r.Headers.Set("Content-Type", "text/html")
		r.Headers.Set("User-Agent", "Chrome/78.0.3904.87 Safari/537.36")
		r.ResponseCharacterEncoding = "utf-8"
        })
	c.OnHTML("body", func(e *colly.HTMLElement) {
		titlename := e.ChildText(".info-title h1")
		fmt.Printf("%s\n", titlename)
	})
</pre>

<pre>
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"golang.org/x/text/encoding/simplifiedchinese"
	"golang.org/x/text/transform"
)

func GbkToUtf8(s []byte) ([]byte, error) {
	reader := transform.NewReader(bytes.NewReader(s), simplifiedchinese.GBK.NewDecoder())
	d, e := ioutil.ReadAll(reader)
	if e != nil {
		return nil, e
	}
	return d, nil
}

func Utf8ToGbk(s []byte) ([]byte, error) {
	reader := transform.NewReader(bytes.NewReader(s), simplifiedchinese.GBK.NewEncoder())
	d, e := ioutil.ReadAll(reader)
	if e != nil {
		return nil, e
	}
	return d, nil
}

func main() {
	s := "女超人第五季"
	gbk, err := Utf8ToGbk([]byte(s))
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("use gbk:", string(gbk))
	}

	utf8, err := GbkToUtf8(gbk)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("use utf-8:", string(utf8))
	}
}
--------------
use gbk: Ů���˵��弾
use utf-8: 女超人第五季
<pre>

**Comment by asciimoo** [comment]
Have you tried `Collector.DetectCharset = true`?
```
   // DetectCharset can enable character encoding detection for non-utf8 response bodies
   // without explicit charset declaration. This feature uses https://github.com/saintfish/chardet
```

**Comment by gouki777** [comment]
thank you. it is good.
<per>
	c.OnHTML("body", func(e *colly.HTMLElement) {
		c.DetectCharset = true
		titlename := e.ChildText(".info-title h1")
		fmt.Printf("%s\n",titlename)
	})
</pre>
