### ISSUE TITLE
Docs do not match the released version

### ISSUE THREAD

**Issue by n-i-x** [gocolly/colly#406]
A new method (HTMLElement.ChildTexts) popped up in the docs https://godoc.org/github.com/gocolly/colly#HTMLElement.ChildTexts but does not exist in v1.2.0. It looks like the relevant code was added in October:

https://github.com/gocolly/colly/commit/18c33ec1db6b6f854c0fc2ebe6b3862e9752820e

Please update the docs, or even better... release a new version since that looks really handy!

**Comment by asciimoo** [comment]
New version released and as I see the documentation is correct.
