### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by AndyZoeng** [gocolly/colly#409]

**Comment by bukowa** [comment]
````golang
c.WithTransport(&http.Transport{
    TLSClientConfig:&tls.Config{InsecureSkipVerify: true},
})
````

**Comment by asciimoo** [comment]
@bukowa thanks for the answer.

**Comment by fredgan** [comment]
May I ask that how does this come? Is  the certificate is changed by the website? But the certificate in the website shows normal in the Chrome. Such as `https://www.iif.com/Advocacy`, it used to be normal.  but recently it shows the error.
