### ISSUE TITLE
rendered pages

### ISSUE THREAD

**Issue by LucaPaterlini** [gocolly/colly#414]
hello,
is there a method that allows the rendering of the page before starting to parse it?
something similar to phantomJs or https://github.com/chromedp/chromedp
just for the rendering of the page, I mean all the tags and attributes added at the loading time of the page.

My understanding is that the default settings of Colly is allowing to parse only the plain HTML source code.

**Comment by asciimoo** [comment]
Colly can't render pages currently - check #4 for more info.
