### ISSUE TITLE
Using xpath selectors with html pages

### ISSUE THREAD

**Issue by pauldid** [gocolly/colly#415]
I'd like to use xpath selectors to extract data from html pages (which I used to do with Scrapy).
However it seems that xpath selectors are limited to xml pages in colly. Could you confirm this?

**Comment by asciimoo** [comment]
Use OnHTML callbacks to be able to use xpaths on HTML sites.

**Comment by slfmessi** [comment]
It is actually what I need，and I think it is a good design.
Is where any approach to implement it?

**Comment by pauldid** [comment]
Do you plan to implement xpath with HTML at some point?
