### ISSUE TITLE
Can not convert charset gb18030 to utf-8 due to chardet

### ISSUE THREAD

**Issue by xtrees** [gocolly/colly#421]
html gb18030
chardet detect as GB-gb18030  
so content type  => text/plain; charset=GB-18030,
the charset package can't convert the content to utf-8 correctly
it should be text/plain; charset=GB18030 

fixCharset  is a private func  I can do nothing about it , 
what about adding one callback  in fixCharset func ?

**Comment by asciimoo** [comment]
Have you tried turning on `Collector.DetectCharset`? Also, you can set `Request.ResponseCharacterEncoding` to force the decoding of the response.
