### ISSUE TITLE
issue with ssl  certificate and missing http/https prefix in url to visit

### ISSUE THREAD

**Issue by yohaiaz** [gocolly/colly#422]
we are testing a  migration to colly and we are facing  2  issues.

first issue:
we  have a lot of  urls to check they all looks like "example.com" without prefix "http://www." or "https://www."
a normal browser like chrome or safari knows how to resolve "domain.com" to "http://www.example.com" or "https://www.example.com". sdk like scrapy or wget knows also doing that. Is it something I'm missing with colly's configuration ? I don't want to use extrapolation techniques and add the prefix to the url "http://" or crawl twice one time with "http://" and another time with "https://".

second issue:
when I query explicitly a url that require "https://" and the website has no valid ssl certificate. I got an error like "x509: certificate has expired or is not yet valid"
 Is it something I'm missing with colly's configuration ?

Thanks

**Comment by LeMoussel** [comment]
For the first issue, by default Chrome & FF resolve example.com to http://example.com/
Note: Chrome and FF adds systematically `/` at the end if missing.

You may add a scheme like this:
if !strings.HasPrefix(link, "http://") && !strings.HasPrefix(link, "https://") {
        link = "http://" + link
}

**Comment by asciimoo** [comment]
>  when I query explicitly a url that require "https://" and the website has no valid ssl certificate. I got an error like "x509: certificate has expired or is not yet valid"

You can set a custom http client which ignores certificate errors: https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#Collector.SetClient
