### ISSUE TITLE
Number of query for collect data

### ISSUE THREAD

**Issue by ozzyst** [gocolly/colly#423]
Hello!
I use Colly for parse _table_ elements. I get all _tr_ from the table. How I can stop iteration after N element, eg 10. I mean I want get first 10 (20-30-40-50...) rows of table and to stop collect data.

I found issue in yur repo with same problem, but I didn`t find decision.

**Comment by asciimoo** [comment]
What about something like this:
```golang
c.OnHTML("table", func(e *colly.HTMLElement) {
    e.ForEachWithBreak("tr", func(i int, tr *colly.HTMLElement) bool {
        if(i == 10) {
            return false
        }
        // handle the first 10 element here
        return true
    })
})

```
