### ISSUE TITLE
Scrapping stops at semi-colons

### ISSUE THREAD

**Issue by BardoBravo** [gocolly/colly#428]
Hi,

I am using Colly for some time, and got an incovenient issue now. For some reason I could not bypass, for a given website XML the data retrieval stops, gathering only the data up to an existing semi-colon (";").

Below you can find the website XML:
```xml
<div class="lista-imovel-content-itens">
					
	<link rel="stylesheet" href="/geral/css/slider.css" type="text/css">
	
	
	<script type="text/javascript" src="/geral/js/slider/jquery.numberformatter-1.2.3.js"></script>
	<script type="text/javascript" src="/geral/js/slider/tmpl.js"></script>
	<script type="text/javascript" src="/geral/js/slider/jquery.dependClass-0.1.js"></script>
	<script type="text/javascript" src="/geral/js/slider/draggable-0.1.js"></script>
	<script type="text/javascript" src="/geral/js/slider/jquery.slider.js"></script>    

<script type="text/javascript" src="/geral/js/slider/jshashtable-2.1_src.js"></script>
<script language="javascript" type="text/javascript" src="/geral/js/ajax1.js?c=3"></script>
<script type="text/javascript" src="/geral/js/slider/jquery-1.7.1.js"></script>
<style>...</style>
<script>...</script>
	
<!-- search sidebar -->
<div id="buscar-toggle-sidebar" class="search-box">...</div>	
<script type="text/javascript">
$('.dinheiro').maskMoney();
</script>	
				<!-- // -->			
					<div class="grid-itens" id="Listagem">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.0.2/css/hover-min.css">
<link rel="stylesheet" type="text/css" href="/geral/css/listalistagem.css?v=18">
 


<script>...</script>

<style type="text/css">...</style>
<div class="grid-list-header">...</div>
<form name="results">...</form>
	
<div id="divBusca">
<ul class="gl list">

```

After the **$('.dinheiro').maskMoney();** script call, nothing is retrieved from Colly, even though there are other tags like **div id="divBusca"**, as seen in the code snip. I am not sure, but it seems to be related to that semi-colon.

The last content is always displayed with that part, as we can see as return from console:
**5 suites + $('.dinheiro').maskMoney(); ]**

If I try to collect data (tags) that come after that script call, the return is empty.

If you would like to check the source website, you can look at [this link](https://www.lifeimob.com.br/index.asp?id_pagina=8&OrdernarPor=Preco%20DESC&ValorDe=0&ValorAte=500000000&cidade=3326)

Hugs

**Comment by asciimoo** [comment]
Could you share the scraper code too?

**Comment by BardoBravo** [comment]
Hello,
The calling code is:
```go
func (platform LifeImob) crawl(config Config, exporter Exporter) *colly.Collector {
	c := platform.NewCollector(config)

	c.OnXML("//div[contains(@class, 'grid-list-header')", func(e *colly.XMLElement) {
		log.Print("Starting LifeImob Storage")
		item := platform.parseItem(e)

		//exporter.storeDocument(item)

		exporter.write(item)
	})

	c.Visit("https://www.lifeimob.com.br/index.asp?id_pagina=8&OrdernarPor=Preco%20DESC&ValorDe=0&ValorAte=500000000&cidade=3326")
	return c
}
```

When retrieving from *"//div[contains(@class, 'grid-list-header')"* the return is empty (the tag is after the script call). If I get from *"//div[contains(@class, 'search-box')"*, the scrapped data goes until the script call.

**Comment by asciimoo** [comment]
This HTML page isn't a valid XML document so OnXML fails, try OnHTML with css selectors.

**Comment by BardoBravo** [comment]
Hello,

I did try with onHTML and the same issue happens.

If I look for div class='grid-itens', it finds the scrapper, but I am not able to dig it.
If I look for one of the internal "DIVs", like 'grid-list-item',  nothing is retrieved.

It happens for both calls (XML and HTML):

```go
c.OnXML("//*[contains(@class, 'grid-list-header')]", func(e *colly.XMLElement) {
		log.Print("Starting LifeImob Storage")
		item := platform.parseItem(e)

		//exporter.storeDocument(item)

		exporter.write(item)
	})

 c.OnHTML("div[class=grid-list-header]", func(e *colly.HTMLElement) {
		log.Print("Starting LifeImob Storage")
		item := platform.parseItem(e)

		//exporter.storeDocument(item)

		exporter.write(item)
	}) */
```

The used page for reference has the following HTML structure:
```html
<div class="grid-itens" id="Listagem">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.0.2/css/hover-min.css">
<link rel="stylesheet" type="text/css" href="/geral/css/listalistagem.css?v=18">
 


<div class="grid-list-header">  

<div class="historico">
                <div class="frase-hist">
                  <a href="/home">  <span>
                        <i class="fa fa-home" aria-hidden="true"></i>
                        <i class="fa fa-caret-right" aria-hidden="true"></i>
                    </span></a>
```

Again, there are some scripts in-between those DIV tags.

Any thoughts?

**Comment by asciimoo** [comment]
>  c.OnHTML("div[class=grid-list-header]", func(e *colly.HTMLElement) {

OnHTML accepts css selectors like "div.grid-list-header".

I've checked the source code of the url and it doesn't contain any div with the class name `grid-list-header`. Those divs come from an ajax request (you can check it in your browser inspectors network tab). The url is https://www.lifeimob.com.br/geral/paginas/listaListagem.asp?atualiza=1&id_pagina=8&OrdernarPor=Preco%20DESC&ValorDe=0&ValorAte=500000000&cidade=3326&&atualiza=1&0.8983601713954388_1581036242094 . You should fetch this url with colly.

**Comment by BardoBravo** [comment]
OK. I will try it out. Thanks!
