### ISSUE TITLE
HTMLElement: Text property issue

### ISSUE THREAD

**Issue by donutloop** [gocolly/colly#430]
if I want to extract the following HTML element structure then I get a bad text value back

Raw data example:

![issue](https://user-images.githubusercontent.com/9432921/71772171-e25a3400-2f46-11ea-8866-db2c2cb5b49e.png)

Processed data example:

1875 South Grant StreetSuite 600San Mateo, CA 94402

Expected value: 

1875 South Grant Street Suite 600 San Mateo, CA 94402

Code snippet:

```
    textFunc := func(e *colly.HTMLElement) {
		_, ok := set[e.Text]
		if !ok {
			set[e.Text] = e.Text
		}
	}
	c.OnHTML("title", textFunc)

```

is it possible to overwrite the replace function for these HTML tags (\<br\>)?

**Comment by asciimoo** [comment]
You can get the inner HTML by calling `e.DOM.Html()`, then the `<br />`s can be replaced from the scraper.
