### ISSUE TITLE
How to make different type request depending on URL extensions?

### ISSUE THREAD

**Issue by LeMoussel** [gocolly/colly#435]
Is it possible to have different type request depending on the URL extension like `.jpg`, `.png`, ...
For example for the images (jpg, png, ...) use only HEAD request, no GET request.
Maybe by overwriting [Visit()](https://github.com/gocolly/colly/blob/master/colly.go#L410) function ?

**Comment by asciimoo** [comment]
You can use `Collector.Request`[0] to create any kind of custom requests in a wrapper.

[0] https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#Collector.Request
