### ISSUE TITLE
When I set header to application/json, I can't get the data (is nil) of response.Request.Body

### ISSUE THREAD

**Issue by hookover** [gocolly/colly#438]
i set header to：
r.Headers.Set("content-type", "application/json; charset=utf-8")

and use c.PostRaw() method, like:
c.PostRaw(hostUrl, []byte(fmt.Sprintf(`{"perPage":100,"page":%d}`, storage.Page())))

in c.OnError or c.OnResponse methods print request.Body is nil log.Println(response.Request.Body) //is nil

**Comment by hookover** [comment]
Or how to get the id of a unique processing process？

**Comment by hookover** [comment]
how can reRead request.Body (io.Reader)

**Comment by asciimoo** [comment]
What is the output of `PostRaw`? It returns with an error, perhaps it has information about what goes wrong.

**Comment by hookover** [comment]
> What is the output of `PostRaw`? It returns with an error, perhaps it has information about what goes wrong.

I can get normal and accurate server response data, and error equals nil. I think because request.Body is a io.Reader type, this data type is only allowed to be read once, and it has been read at the time of the request, so I won't be able to read it again.

**Comment by asciimoo** [comment]
What is the status code of the result?

**Comment by hookover** [comment]
> What is the status code of the response?

status code is 200

**Comment by asciimoo** [comment]
it works for me with this test code:
```golang
package main

import (
    "fmt"
    "github.com/gocolly/colly/v2"
)

func main() {
    c := colly.NewCollector()
    c.OnRequest(func(r *colly.Request) {
        r.Headers.Set("content-type", "application/json; charset=utf-8")
    })
    c.OnResponse(func(r *colly.Response) {
        fmt.Println(string(r.Body))
    })
    c.PostRaw("https://httpbin.org/post", []byte(`{"perPage":100,"page":1337}`))
}

```

**Comment by maxight** [comment]
Thank you for the example. The only thing that it shows response.Body, and the question was about response.Request.Body.
Can you please let us know if there is a way to display the request body (nor response body) in OnResponse?
Thanks
