### ISSUE TITLE
DOM.Find won't work if element has class name strating with number

### ISSUE THREAD

**Issue by devd251993** [gocolly/colly#439]
I am trying to get elements using DOM.Find selector. This works fine with normal class names. But for elements which have class name staring with number DOM.Find returns no elements.  I am using the following code to get a list of elements having class name 1W. 

![image](https://user-images.githubusercontent.com/6411651/73067102-c3a7e700-3ecd-11ea-83da-d685f7cbfee4.png)

The list here is empty. But the actual html page has td elements with class 1W as shown in image below.
 ![image](https://user-images.githubusercontent.com/6411651/73066809-0b7a3e80-3ecd-11ea-9853-1984e9d46b08.png)

I don't know if I am doing something wrong. Please help me out here.
Thank You.

**Comment by asciimoo** [comment]
`Find` only works with full css class names like `"1W text-right"`.

**Comment by devd251993** [comment]
@asciimoo I tried giving full CSS class name also but still I am not getting anything.

**Comment by asciimoo** [comment]
Here's a little example with semantic-ui.com which uses space separated class names too:
```golang
c := colly.NewCollector()
c.OnHTML(".ui.vertical.inverted.sidebar.menu", func(e *colly.HTMLElement) {
    fmt.Println(e.DOM.Html())
})
c.Visit("https://semantic-ui.com/")
```
