### ISSUE TITLE
save session as file

### ISSUE THREAD

**Issue by codenoid** [gocolly/colly#442]

**Comment by codenoid** [comment]
right, current golang cookiejar not supported for saving session to a file, how about 

https://github.com/juju/persistent-cookiejar use ?

**Comment by asciimoo** [comment]
What is the purpose of this feature?

**Comment by codenoid** [comment]
if every app boot we do login, some sites can detect our account as bot

**Comment by asciimoo** [comment]
You can retrieve cookies with https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#Collector.Cookies and load it to a custom cookie jar: https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#Collector.SetCookieJar

**Comment by codenoid** [comment]
after month of trying, no luck

**Comment by batara666** [comment]
seriously ???
