### ISSUE TITLE
v2.0.0 is unuseable, please release a v2.0.2 tag

### ISSUE THREAD

**Issue by hyacinthus** [gocolly/colly#443]
Because of the old 2.0.1 tag,
when I use `go get -u` command to update pkgs,
the colly will update to old 2.0.1

If you released a v2.0.2 tag, I think everything will ok.

**Comment by asciimoo** [comment]
v2.0.1 is newer than v2.0.0

**Comment by hyacinthus** [comment]
Thank you and sorry , I'm confused by github release order... :)

**Comment by asciimoo** [comment]
Yeah, I've just checked the tags page of github, now I understand your issue. Dont know why, but github orders it by modification date and I modified the 2.0.0 tag after the 2.0.1. Thanks for pointing out.
