### ISSUE TITLE
When is colly completly done?

### ISSUE THREAD

**Issue by bukowa** [gocolly/colly#444]
Hey there! I want to use `semaphore` to limit `colly` async requests count. Right now i think of using that:
````golang
c.OnResponse(func(response *colly.Response) {
	Semaphore.Release(1)
})

c.OnError(func(response *colly.Response, e error) {
	Semaphore.Release(1)
})
````
But is this the right way to make sure i won't lost a `semaphore` in between?

**Comment by asciimoo** [comment]
@bukowa there is a queue implementation in colly which has exactly the same functionality: https://godoc.org/github.com/gocolly/colly/queue , http://go-colly.org/docs/examples/queue/

**Comment by bukowa** [comment]
Ok thanks but it doesnt answer my question

**Comment by asciimoo** [comment]
You can check the code of the queue to figure out how it handles this issue

**Comment by bukowa** [comment]
Ok thanks a lot!

**Comment by bukowa** [comment]
Just to let you know, `queue` implementations uses 10% of cpu, while `semaphore` 0.2%, so it all depends on the use case.

**Comment by asciimoo** [comment]
> Just to let you know, queue implementations uses 10% of cpu, while semaphore 0.2%, so it all depends on the use case.

This is kind of strange because queue doesn't do much computation. Do you have a test code available where you measured these differences?

**Comment by bukowa** [comment]
Sorry, its deleted :(
