### ISSUE TITLE
When I set header to application/json, I can't get the data of response.Request.Body, Continue

### ISSUE THREAD

**Issue by maxight** [gocolly/colly#445]
Problem: cannot read response.Request.Body in OnResponse.

Actually, it's #438 , which eventually was closed without a clear answer to the question.
I really appreciate you for all your efforts and for this amazing project, and for the code snippet in #438 , but unfortunately it shows us how to read response body, but not **request** body in OnResponse.

Let me tell you a real-world example. I make a lot of requests at the same time, to the same URL with different POST payload. Now, I got a lot of callbacks in OnResponse, and I need a way to identify the initial request (which request it belongs to). If URLs were different - it's all clear, I just could parse response.Request.URL and go with it. But when URL is the same for all requests, and only payload is different, I need somehow to parse response.Request.Body - can you please help me there?

The only ugly solution I had on my mind is to cache request payloads in advance, assign some IDs for each of them, and add some fake request header like "My-Request-ID: 123". Then, in OnResponse I can read that header and find appropriate request payload. But I really don't like this solution, because it requires to pass additional suspicious header to the server.

So, any suggestions on reading response.Request.Body, or any other solution of the problem are more than welcome.

**Comment by asciimoo** [comment]
Sorry, I misunderstood your question. I need further investigation about getting the *request* body from the response. As a workaround, you can store the content of `Request.Body` in `Request.Ctx` and it is available from the `Response` too.

**Comment by asciimoo** [comment]
> I need further investigation about getting the request body from the response.

I did it and the issue is caused by `Request.Body`'s type. It is a `reader` instance, so after reading the content there is no way to read it again. The purpose of being a `reader` is to handle big payloads (e.g. large file uploads) without storing it in the memory. So if you want to identify the request from the response, use the `Ctx`.

Does this solve your problem?

**Comment by maxight** [comment]
Thank you very much for your answer.

Yes, now everything looks clear and makes sense. Special thanks for pointing out `Ctx` as solution for identifying requests from the response.
