### ISSUE TITLE
Collect visited URLs

### ISSUE THREAD

**Issue by danielezer** [gocolly/colly#465]
Hello, I'm trying to create a scraper that would just return the visited URLs. Since I have a bunch of nested URLs I want to use the Async option. However, this means I have to use a channel to store the retrieved URLs and it just doesn't work out for me. 

For example, this code:
```
package main

import (
	"fmt"
	"github.com/gocolly/colly"
	"strings"
)

func main() {
	urls := make(chan string)

	c := colly.NewCollector(
		colly.Async(true),
	)
	c.Limit(&colly.LimitRule{DomainGlob: "*", Parallelism: 50})

	// On every a element which has href attribute call callback
	c.OnHTML("a[href]", func(e *colly.HTMLElement) {
		link := e.Attr("href")
		// Print link
		// Visit link found on page
		// Only those links are visited which are in AllowedDomains
		c.Visit(e.Request.AbsoluteURL(link))
	})

	// Before making a request print "Visiting ..."
	c.OnRequest(func(r *colly.Request) {
		l := r.URL.String()
		if ! strings.HasSuffix(l, "/") {
			fmt.Println("Found link ", l)
			urls <- l
		} else {
			fmt.Println("Found directory ", l)
		}
	})

	// Start scraping on https://hackerspaces.org
	url := "https://my-url/"
	c.Visit(url)

	var result []string
	for u := range urls {
		fmt.Printf("Read value from channel - %v", u)
		result = append(result, u)
	}

	println(result)

}
```

This just halts after it reads everything because the channel is still open.
I'm not sure when I can close the channel because the goroutines are still running in the background.
If I use `c.wait()` and then close the channel, it also doesn't work. 
Do you have a suggestion on how to get this working?

**Comment by SeanBE** [comment]
The reason calling `c.Wait()` before the loop isn't working for you is because the goroutines are blocked at the unbuffered channel (`urls <- l`). 
One solution is to spin up a new goroutine after calling `c.Visit(url)`:
```go
go func() {
	c.Wait()
	close(urls)
}()
```
The wait command will return when all jobs are completed, allowing your channel to close and terminating the loop on the main goroutine.

**Comment by danielezer** [comment]
Thank you @SeanBE, that's awesome! it worked!
