### ISSUE TITLE
Add a Close() method to the storage.Storage interface

### ISSUE THREAD

**Issue by TheGreatPanda** [gocolly/colly#467]
The storage.Storage interface (used to implement alternative storage backends) currently doesn't have a method that gets called after Colly finishes crawling. This can cause problems for backends that rely on files or database connections. I noticed that a number of backends, like storage.InMemoryStorage and the sqlite3 backend, implement a Close() method, but I couldn't find any places this gets called.

Is there a reason this isn't implemented? If not, I'd be happy to submit a pull request.

**Comment by TheGreatPanda** [comment]
Just found out the method used to exist, but was removed in https://github.com/gocolly/colly/commit/6c43646a676c5034a555f7155b84c214e00f7e5c by @asciimoo. @asciimoo, do you perhaps remember the reason this was removed?

**Comment by felix** [comment]
The interface should only define the methods that Colly requires. It does not necessarily require a Close() method, but the storage backend may. So create the backend, defer the Close() call and pass the storage backend to Colly.
```go
        storage, _ := bolt.New("blah.db")
        defer storage.Close()

        q, _ := queue.New(1, storage)
````

**Comment by asciimoo** [comment]
@felix thanks for answering the question, you are right. Close method isn't necessary for every instance of the interface.
