### ISSUE TITLE
How to pin request to ip address

### ISSUE THREAD

**Issue by wzije** [gocolly/colly#471]
Hi, I have a problem to crawl a web because the domain redirects to IP address. I Used the command normally or request with IP address like`visit("ip_address")` not working. then I try request using curl `curl [domain]`, it's still not working, but when I am using curl command `curl domain --resolve domain:ip_address: port` it's working nicely.

so what can I do to implement `--resolve`  in colly.
Sorry for my English.

Thanks.

**Comment by asalih** [comment]
There isn't any direct support to change dial context on colly. However you can add a single line to your host file whether to resolve an ip address for a domain. Have you tried it?

**Comment by asciimoo** [comment]
Seems like it is possible: https://stackoverflow.com/questions/40624248/golang-force-http-request-to-specific-ip-similar-to-curl-resolve
