### ISSUE TITLE
"github.com/gocolly/colly/v2/..." matched no packages

### ISSUE THREAD

**Issue by zen37** [gocolly/colly#475]
As per Installation on https://github.com/gocolly/colly I ran 
`go get -u github.com/gocolly/colly/v2/...`
and 
`go: warning: "github.com/gocolly/colly/v2/..." matched no packages`

**Comment by djarbz** [comment]
Update your version of GO, that's what I had to do.

**Comment by zen37** [comment]
I have 
go1.13.5 darwin/amd64. 
Is it not sufficient?

**Comment by djarbz** [comment]
Should be, are you using go mod?

**Comment by zen37** [comment]
I am not, at least I don't think I am :)

**Comment by djarbz** [comment]
I'm pretty sure packages that end in v# require go mod

**Comment by zen37** [comment]
README.md says nothing about it, just 
`go get -u github.com/gocolly/colly/v2/...`
and I dully did this :)

**Comment by djarbz** [comment]
It's not specific to this package, it's a GO thing.

**Comment by zen37** [comment]
ok, thank you will have read further about it, I am a very beginner.

**Comment by djarbz** [comment]
No problem, we all have to start somewhere!
If that works for you, make sure you note it on this issue.
Then, perhaps the owner of the repo can make a note in the documentation.

**Comment by IPreferWater** [comment]
here you can learn about [go module](https://github.com/golang/go/wiki/Modules)

You will find 

> In Go 1.14, module support is considered ready for production use, and all users are encouraged to migrate to modules from other dependency management systems.

so you should go to the root of your project and
`go mod init github.com/zen37/your-project-name`

then you will have a go.sum and go.mod file & you will be able to run your go-project

**Comment by zen37** [comment]
Yes, it worked now.
