### ISSUE TITLE
How to get Meta Tags like ok:type?

### ISSUE THREAD

**Issue by Tobias-Keller** [gocolly/colly#477]
Hi, i'm new to colly and trying to get a meta tag...
code on website:
`<meta property="og:type" content="product" />`

how do i get this element in colly?

**Comment by asciimoo** [comment]
You can iterate through all the meta elements and check the `property` attribute in an OnHTML callback.

**Comment by gianpaj** [comment]
For anybody else looking at this:

```go
c.OnHTML("html", func(e *colly.HTMLElement) {
	meta := strings.Split(e.ChildAttr("meta[name=\"twitter:url\"]", "content"), "\n")[0]
	fmt.Printf("meta: %q\n", meta)
})
```
