### ISSUE TITLE
Custom http retryable client

### ISSUE THREAD

**Issue by danielezer** [gocolly/colly#480]
I'm using a go retryable HTTP client from this package: https://github.com/hashicorp/go-retryablehttp. Is it possible to set this as a custom HTTP client? I saw the setClient method but it only seems to support the *http.Client type... 
It supports basically all the same methods as the standard HTTP client, so it would be really cool if there was a way to use this

**Comment by asciimoo** [comment]
The project readme mentions the following:

> It's possible to convert a *retryablehttp.Client directly to a *http.Client. This makes use of retryablehttp broadly applicable with minimal effort. Simply configure a *retryablehttp.Client as you wish, and then call StandardClient()

As far as I understand, this solves your problem.

**Comment by danielezer** [comment]
Nice catch @asciimoo, thanks!
