### ISSUE TITLE
Race condition when using Parrellelism and Proxies

### ISSUE THREAD

**Issue by i25959341** [gocolly/colly#482]
Got races when enabling parrellel thread,

Need to use a thread safe array

Previous write at 0x00c000518298 by goroutine 62:
  sync/atomic.AddInt32()
      /usr/local/Cellar/go/1.14/libexec/src/runtime/race_amd64.s:269 +0xb
  github.com/gocolly/colly/v2/proxy.(*roundRobinSwitcher).GetProxy()
      /Users/karlsonlee/go/pkg/mod/github.com/gocolly/colly/v2@v2.0.1/proxy/proxy.go:33 +0x118

**Comment by asciimoo** [comment]
Fixed in #483
