### ISSUE TITLE
collect metrics from gocolly scrpaing

### ISSUE THREAD

**Issue by x0rzkov** [gocolly/colly#486]
Hi guys,

Hope you are all well again !

I was wondering if there is a way to collect metrics from gocolly scraping.

Found an interesting package abstracting stats collection
https://github.com/segmentio/stats

Is there a simple way to hook segmentio's stats package to the gocolly's code ?
Is there a way to extract statistics from gocolly like from [gargantua](https://github.com/andreaskoch/gargantua) ?
![garguantua dashboard](https://raw.githubusercontent.com/andreaskoch/gargantua/develop/files/gargantua-in-action-crawling-a-website.gif)
Gif: https://raw.githubusercontent.com/andreaskoch/gargantua/develop/files/gargantua-in-action-crawling-a-website.gif

Thanks in advance for any insights or inputs on that topic.

Cheers,
X

**Comment by asciimoo** [comment]
You can create a custom debugger and pass it to a collector: https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#Collector.SetDebugger .

I think it can solve your issue.
