### ISSUE TITLE
Outdated Example for https://coinmarketcap.com/

### ISSUE THREAD

**Issue by kewei5zhang** [gocolly/colly#494]
First of all, thanks for putting together colly which is definitely the goto tool now when talking about web crawling. 

Just follow the example and find the [coinmarketcap.com](https://github.com/gocolly/colly/blob/master/_examples/cryptocoinmarketcap/cryptocoinmarketcap.go) example has been outdated. Here is the PR for the update to date website HTML: https://github.com/gocolly/colly/pull/493

**Comment by asciimoo** [comment]
fixed by #493
