### ISSUE TITLE
Proxy switcher always uses same proxy

### ISSUE THREAD

**Issue by alexxxPopa** [gocolly/colly#499]
Pretty new to gocolly, but I try to follow the examples for the default built in proxy switcher.

`rp, err := proxy.RoundRobinProxySwitcher("socks5://a", "socks5://b")
	if err != nil {
		log.Fatal(err)
	}
	c.SetProxyFunc(rp)`

the problem I am encountering with this code is that it always uses the same proxy, it nevers really  splits requests to a proxy and to b proxy.

Am I missing something?
any help is appreciated

**Comment by scholar-ink** [comment]
how to solve

**Comment by perelin** [comment]
This was closed, but what was the solution?

**Comment by POFK** [comment]
I found the same problem and got the solution from #399 and #567 
If your requestion is by http not https, you will found there is no same problem. If you request https webpage, you can set the `DisableKeepAlives` as `true` to make sure that the ProxyFunc is called on every requestion.
```
c.WithTransport(&http.Transport{
    DisableKeepAlives: true,
})
```
