### ISSUE TITLE
Add HTTPS to website

### ISSUE THREAD

**Issue by titanous** [gocolly/colly#507]
Hi! I was looking at Colly, and noticed that your website does not support HTTPS.

Enabling HTTPS for your website is pretty easy (I recommend using Caddy) and helps protect everyone that visits it. You can see some reasons why you should do this here: https://doesmysiteneedhttps.com

I'd be happy to answer any questions if you want some help!

**Comment by asciimoo** [comment]
Thanks for your notice, i'm going to add ssl to the site asap.
