### ISSUE TITLE
Context Get method should return interface type

### ISSUE THREAD

**Issue by markelog** [gocolly/colly#51]
Currently, you can put anything in the context. Which was allowed after the fix for [this](https://github.com/gocolly/colly/issues/47) issue. 
But it will type assert any value to a string [nevertheless](https://github.com/gocolly/colly/blob/03d1dcd43c6e316bac5d5d4cc98cc642b4cbe8db/colly.go#L806).

I propose to allow to retrieve an interface instead. Which would be a breaking change

**Comment by asciimoo** [comment]
@markelog `context.GetAny()` exists for this purpose: https://godoc.org/github.com/gocolly/colly#Context.GetAny

**Comment by markelog** [comment]
I see, thanks, missed that one
