### ISSUE TITLE
How to control the suspension or stop of the collector？

### ISSUE THREAD

**Issue by Beatrice950201** [gocolly/colly#513]
I now need a button to control the collector to start and stop; Are there any solutions in place? Because as far as I know there is no such internal method! I am looking forward to your reply. Thank you!

**Comment by asciimoo** [comment]
Could you specify your use-case in a bit more detail? You can use https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#Request.Abort in an `OnRequest` callback to cancel a request.

**Comment by Beatrice950201** [comment]
> Could you specify your use-case in a bit more detail? You can use https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#Request.Abort in an `OnRequest` callback to cancel a request.

I will try to use the method you provided; Thank you for your reply!
