### ISSUE TITLE
AllowedDomains retrieval from database

### ISSUE THREAD

**Issue by sebastiaanvduijn** [gocolly/colly#514]
I am retrieving my alloweddomain list from a database as []string. Since the colly.AllowedDomains only accepts a string I have converted the []string to string using strings.Join(urls, ",").

This generates a comma separated list but Colly takes the whole list as a single domain.

**Comment by WGH-** [comment]
No, it accepts multiple strings. Please refer to https://golang.org/ref/spec#Passing_arguments_to_..._parameters

**Comment by sebastiaanvduijn** [comment]
> No, it accepts multiple strings. Please refer to https://golang.org/ref/spec#Passing_arguments_to_..._parameters

True fact. Thanks!
