### ISSUE TITLE
How to send request using HTTP/2.0 ?

### ISSUE THREAD

**Issue by gopkg-dev** [gocolly/colly#515]
I have a target site after testing http/1.1 will prompt the robot, http/2.0 access is normal, how to do now?

**Comment by asalih** [comment]
Default transport is using http1.1. It seems like this should be implemented in but also http2 transport is not fully supported as like http1.1 e.g there isn't any proxy support yet so this means implementing it can cause some inconvenience at the moment.
http2 proxy issue;
https://github.com/golang/go/issues/26479

**Comment by WGH-** [comment]
I'm pretty sure that `http.DefaultTransport` supports HTTP/2.0 and uses it where available.

However, if you configure a proxy server, Colly will initialize a new `http.Transport` instance, which won't have HTTP/2 support by default. Were you using proxies, @gopkg-dev?
