### ISSUE TITLE
Support for article / aside / section tags

### ISSUE THREAD

**Issue by stemsin** [gocolly/colly#519]
Evening,

First, thanks for colly! It's absolutely fantastic. Works fine on my tasks where there are traditional sites, but I'm facing issues with Autotrader specifically.

I wanted to check if it's missing support for **article / aside / section** tags or it's me doing something wrong. Any help is appreciated.

Task: get the car price from https://www.autotrader.co.uk/classified/advert/202003138387844 page.

Stripped down code:
`	c := colly.NewCollector()

	c.OnHTML("h2.price-confidence__price", func(e *colly.HTMLElement) {
		s := e.ChildText("span")
		log.Println(s)
	})

	c.Visit("https://www.autotrader.co.uk/classified/advert/202003138387844")

	c.Wait()
`

Result: OnHTML functon is never called.

**Comment by asciimoo** [comment]
It is loaded by javascript, if you look at the page source (not from inspector, it shows the rendered html, not the original one), you can't find any tags with `price-confidence__price` class. It is loaded from an AJAX request:  https://www.autotrader.co.uk/json/fpa/initial/202003138387844?guid=f384427f-8cf2-4e62-a848-45c8e9812477 .
You can fetch this request to collect data or get the price from other tags - e.g. `og:description` meta tag contains the price.

**Comment by stemsin** [comment]
Thanks, clear. Is it possible to use some kind of headless renderer with colly for JS-based sites? Like chromedp for or any other.
Any example?
Otherwise, it would be close to a full-text parsing of the sites.

**Comment by asciimoo** [comment]
there is an open PR about this topic: https://github.com/gocolly/colly/pull/503
