### ISSUE TITLE
Query selector in callback functon

### ISSUE THREAD

**Issue by stemsin** [gocolly/colly#523]
I need to dynamically generate a callback function and inside I will handle the logic. Something like below. The issue is the callback function does not have the context, which query it was used for, but only the response. Is there a way to solve it?
```
	for _, ci := range sReq.req.Child.Item {
		log.Printf("Setting onChildHTML for [%s]\n", ci.Block) 

		detailCollector.OnHTML(ci.Block, func(e *colly.HTMLElement) { // correct - goquerySelector here
			log.Printf("Calling onChildHTML for [%s]\n", ci.Block) // wrong - always the last used goquerySelector
			sReq.onChildHTML(ci.Block, e)
		})
	}
```

**Comment by asciimoo** [comment]
Wrap callback generation to a function which accepts the selector as parameter and returns with the callback function, in this case you can use the selector value inside the callback I think.

Also, note that it isn't advised to create callbacks inside a callback in general, because it can be called multiple times which leads to duplicated the same callback.

**Comment by stemsin** [comment]
I might have used the wrong wording here. I'm not literally generating the callback function. So, no issues with multiple callbacks.

I want to use the same callback for different selectors and handle them inside. The reason for that is I don't know how many selectors I will have, so need to make them dynamic. And based on a config file I will have some logic for each of the selectors.

The snippet of the function used as the callback in the initial example is here:

```
func (r *mainStruc) onChildHTML(goquerySelector string, e *colly.HTMLElement) {
	for _, i := range r.req.Child.Item {
		// find the current selector
		if i.Block != goquerySelector {
			continue
		}
// do the job here for the specific selector based on selector's configuration
	}
}
```

**Comment by asciimoo** [comment]
> I want to use the same callback for different selectors and handle them inside.

Why?
Anyway, my proposed solution with the function which returns the callback works in this situation.
For example:
```golang
func getCallback(selector string) htmlCallbackContainer {
    return func(e *colly.HTMLElement) {
		log.Printf("current selector: %s", selector)
    })
]
