### ISSUE TITLE
Support for json - OnJSON function?

### ISSUE THREAD

**Issue by ionutnechita** [gocolly/colly#524]
Hi Colly Team,

I need function for parsing multiple json.
It's possible to implement this feature?
And one example for this is important in documentation.

Thanks.

**Comment by WGH-** [comment]
You can certainly parse whatever format you want in `OnResponse`. I'm not sure why you need any special colly support for that.

**Comment by asciimoo** [comment]
I agree with @WGH-, JSON can be handled easily from an `OnResponse` callback.
