### ISSUE TITLE
Distrubuted crawling example(s)

### ISSUE THREAD

**Issue by x0rzkov** [gocolly/colly#527]
Hi guys,

Hope you are doing all well !

I was wondering if it could possible to push a small example of gocolly working in a distributed manner between several clients with sqlite3 databases and central database.

For instance, I found these repositories trying to make some distributions to gocolly crawling:
- https://github.com/sfproductlabs/scrp
- https://github.com/Veerse/reezocar_test

But I am looking for something simple to deploy...

@asciimoo do you have any idea of how to do that ? 

That would bring gocolly to another level and that would be awesome. Isn't it ?

Thanks in advance for your inputs and insights about that.

Have a good week end all !

Cheers,
X

**Comment by asciimoo** [comment]
@x0rzkov there is no need for sqlite middleman database, you can use any persistend strage backend, like redis and connect to it with multiple scrapers distributed.
