### ISSUE TITLE
colly v2 queue consumption not working

### ISSUE THREAD

**Issue by yajiru** [gocolly/colly#540]
I cannot get colly v2 to consume queue for anything other than what was initially present in queue before collector `q.Run(c)`
I am adding to queue on every response, but they are ignored. 
The example below works with `github.com/gocolly/colly` but not with `github.com/gocolly/colly/v2`

```golang
package main

import (
	"github.com/gocolly/colly/v2"
	"github.com/gocolly/colly/v2/queue"
	"log"
	"time"
)

func main() {
	c := colly.NewCollector(
		colly.Async(false),
		colly.AllowURLRevisit(),
	)

	s := &queue.InMemoryQueueStorage{MaxSize: 100000}

	q, _ := queue.New(1, s)

	c.OnResponse(func(rsp *colly.Response) {
		log.Println(rsp.StatusCode)
		q.AddURL("https://google.lt")
	})

	for i := 0; i < 3; i = i + 1 {
		q.AddURL("https://google.com")
	}

	go q.Run(c)

	for true {
		log.Println(q.Size())
		time.Sleep(2 * time.Second)
	}
}

```

**Comment by asciimoo** [comment]
@gopherclass do you have any idea what causes the above issue?

**Comment by gopherclass** [comment]
It's not a bug. Turning off asynchronous mode will solve your problem.

**Asynchronous Mode**
`colly.Async(false)` does not mean asynchronous mode. the argument false has actually no meaning. It turns on asynchronous mode.

```
// Async turns on asynchronous network requests.
func Async(a ...bool) CollectorOption {
	return func(c *Collector) {
		c.Async = true
	}
}
```

If you turns off asynchronous mode, everything will be working as you expect.

```go
func main() {
	c := colly.NewCollector(
		// colly.Async(false),
		colly.AllowURLRevisit(),
	)

...

	go func() {
		log.Print("q.Run() starts") // I add start marker
		q.Run(c)
		log.Print("q.Run() ends") // I add end marker
	}()

...
```

Output:
```
$ go build -o a issue540.go && ./a
2020/09/12 03:08:02 3 <nil>
2020/09/12 03:08:02 q.Run() starts
2020/09/12 03:08:02 200
2020/09/12 03:08:03 200
2020/09/12 03:08:03 200
2020/09/12 03:08:03 200
2020/09/12 03:08:03 200
2020/09/12 03:08:04 1 <nil>
2020/09/12 03:08:04 200
2020/09/12 03:08:04 200
2020/09/12 03:08:04 200
2020/09/12 03:08:04 200
2020/09/12 03:08:04 200
2020/09/12 03:08:05 200
2020/09/12 03:08:05 200
2020/09/12 03:08:05 200
2020/09/12 03:08:05 200
2020/09/12 03:08:05 200
2020/09/12 03:08:05 200
2020/09/12 03:08:06 1 <nil>
2020/09/12 03:08:06 200
2020/09/12 03:08:06 200
2020/09/12 03:08:06 200
2020/09/12 03:08:06 200
2020/09/12 03:08:06 200
2020/09/12 03:08:07 200
2020/09/12 03:08:07 200
...
```

If you want to add more requests to the queue, `AddURL()` must be done on request callback or the goroutine that is executing the request. This is related to memory model and consistency model of Go. On different goroutines, there is no guarantee that variable modified on other goroutine is visible to another goroutine unless two variables synchronize. Though Go uses only sequentially consistency, that innocence might protect you.

**Comment by yajiru** [comment]
Thank you, maybe then bool shouldn't be a colly.Async parameter.. anyway, you can close the issue..

**Comment by asciimoo** [comment]
@gopherclass thanks for your answer.

> Thank you, maybe then bool shouldn't be a colly.Async parameter.. anyway, you can close the issue..

This is true, that parameter has no added value, the only reason it is still there is backward compatibility.
