### ISSUE TITLE
Is there any roadmaps to this project?

### ISSUE THREAD

**Issue by PalanQu** [gocolly/colly#541]
Hi, this is an excellent project and  I want to contribute to this project, is there any roadmaps to this project? or some features need to be done?

**Comment by asciimoo** [comment]
@PalanQu thanks for the offer. We have quite a few open issues and some bugs too. Any help is appreciated.

**Comment by PalanQu** [comment]
@asciimoo  Thanks for your response, I will try to fix these bugs.

**Comment by asciimoo** [comment]
Awesome, thanks a lot!
