### ISSUE TITLE
Limit onHTML to the first hit for one visit

### ISSUE THREAD

**Issue by syerad** [gocolly/colly#542]
**At first thank you for this awesome project! Love working with it!**

Probably it is quite easy to achieve what I want to do, but for now I could not find a solution for that.
In my case I'm crawling through sites and just want to do something  like this:

```
c.OnHTML("div[itemtype]", func(e *colly.HTMLElement) {
  ... just make some stuff on the first div item which will be found on the site. 
}
```

So to sum it up - I just want to do an action on the first hit of a specific site and
don't want to it for every element which will be found on the page.

Thank you in advance!

Kind regards

**Comment by asciimoo** [comment]
You have multiple options:
 - You can select the parent element in the `OnHTML` callback and extract the first div only in the function body.
 - You can create a variable outside of the callback and check if it has value and simply return in the callback function immediately if it already has the wanted value.

**Comment by syerad** [comment]
Thanks for your answer!
