### ISSUE TITLE
Simple race on count fields of Collector type

### ISSUE THREAD

**Issue by iaburton** [gocolly/colly#543]
Hello!

Was browsing the source code and noticed the request/response counters in the Collector type, while incremented atomically are not being loaded atomically, resulting in a data race.

https://github.com/gocolly/colly/blob/v2.1.0/colly.go#L801

**Comment by asciimoo** [comment]
You are right, could you open a PR with the fix?

**Comment by shubham14bajpai** [comment]
@asciimoo I would like to take this up. Can I raise the PR?

**Comment by asciimoo** [comment]
@shubham14bajpai great, thanks. Please open a PR with the fix.
