### ISSUE TITLE
PostRaw returns  no http response data with ContentLength=xxx with Body length 0

### ISSUE THREAD

**Issue by xiaokugua250** [gocolly/colly#545]
when i use c.PostRaw function like this 
`
err = c.PostRaw("http://xxx.xx",[]byte(`{"perPage":100,"page":1337}`))
`
the onrespose return nothings and onError returns `http: ContentLength=27 with Body length 0`
my code is :
`
	
	data:=[]byte(
	`{
    "username": "xasa@gmail.com",
    "timeZone": 8,
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"}`)
	c := colly.NewCollector(colly.Debugger(&debug.LogDebugger{}))
	c.OnRequest(func(request *colly.Request) {
		requestBody,err:= ioutil.ReadAll(request.Body)
		if err!=nil{
			fmt.Println(err)
		}
		fmt.Printf("request body is %s\n",string(requestBody))
		request.Headers.Set("Content-Type", "application/json;charset=UTF-8")
		request.Headers.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0")
		request.Headers.Set("Accept-Encoding", "gzip, deflate")
		request.Headers.Set("Accept-Language", "zh-CN,zh;q=0.9")
	//	request.Headers.Set("Accept","*/*")
	})
	c.OnResponse(func(response *colly.Response) {
		fmt.Println("--->", response.StatusCode)
		resultBody := string(response.Body)
		fmt.Println(resultBody)
	})
	c.OnError(func(response *colly.Response, e error) {
	fmt.Println("error is ",e)
	})
	err = c.PostRaw("http://www.test_api/",data)
	if err != nil {
		fmt.Println(err)
	}
`

it returns 
`eror is  Post "http://www.test_api/": http: ContentLength=27 with Body length 0`

**http: ContentLength=27 with Body length 0**

please help me

**Comment by asciimoo** [comment]
```
requestBody,err:= ioutil.ReadAll(request.Body)
```
This line in the `OnRequest` callback reads out the content of the body before it is submitted. Remove that debug print and it should work.

**Comment by xiaokugua250** [comment]
it worked，thank you 😋
