### ISSUE TITLE
How do I select the checkbox?

### ISSUE THREAD

**Issue by setkyar** [gocolly/colly#552]
For example, something like the following.

![image](https://user-images.githubusercontent.com/4435358/97300961-88d04680-1885-11eb-9e15-7895db935209.png)

The following is the HTML
```
<label class="checkbox-inline">
    <input type="checkbox" name="agreeTC" value="Y">
        I have read, understood, and agree on <a data-toggle="modal" data-target="#termsAndConditon">Terms &amp; Conditions</a>
</label>
```

**Comment by asciimoo** [comment]
You have to create a request to the URL which uses this parameter with `?agreeTC=Y` URL parameter
