### ISSUE TITLE
How to select soap in colly

### ISSUE THREAD

**Issue by Ja7adR** [gocolly/colly#553]
hi 
i'm new golang developer and work using bs4 in python for scrap.
in bs4 i use `soap.select` for get data an element.

example :

`test = soup.select('#f_7954_68_pr > span')[0].text`

but in colly i don't know , how to do it!
Please help for do it.

thank you

**Comment by asciimoo** [comment]
You can do it with and inside OnHTML callbacks. See the examples for more details.

**Comment by Ja7adR** [comment]
> You can do it with and inside OnHTML callbacks. See the examples for more details.

Please, can you show me a sample `OnHTML callbacks` for this `#f_7954_68_pr > span`

thank you
