### ISSUE TITLE
use proxy with ip cool, visit error

### ISSUE THREAD

**Issue by SpectatorNan** [gocolly/colly#556]
when ip set proxy  visit target url

response   forbidden or pramanment redirect

the code:
![image](https://user-images.githubusercontent.com/13959374/98459715-53f2b680-21d8-11eb-9ce8-bb385ed6903b.png)

**Comment by SpectatorNan** [comment]
![image](https://user-images.githubusercontent.com/13959374/98459758-b0ee6c80-21d8-11eb-8ad1-d532f35f4970.png)

**Comment by WGH-** [comment]
Your target website might be whitelisting browser User-Agents, blacklisting known proxies, or doing similar stuff. Please do some effort to debug this issue using e.g. curl to pinpoint the exact reason of the problem (i.e. whether it's proxy, User-Agent or something else). If it still seems to be colly's problem, we'll reopen the issue.
