### ISSUE TITLE
How to set up only one request to use the proxy?

### ISSUE THREAD

**Issue by Wangzhijie2016** [gocolly/colly#56]
I found 
```
rp, err := proxy.RoundRobinProxySwitcher("socks5://127.0.0.1:1337", "socks5://127.0.0.1:1338")
	if err != nil {
		log.Fatal(err)
	}
c.SetProxyFunc(rp)
```
but if i have ten urls need request,  this way is all request to use proxy,  i only want one request to use the proxy, What should I do?

**Comment by asciimoo** [comment]
Ohi,
Proxying only one request can be achieved multiple ways.
You can use two collectors, one with proxy and another without proxy:
```go
c := colly.NewCollector()
c2 := colly.NewCollector()
c2.SetProxy("http://127.0.0.1:8080/")
// ...
```
or you can unset the proxy after the first request:
```go
c := colly.NewCollector()
c.SetProxy("http://127.0.0.1:8080")
c.Visit("http://example.com/")
c.SetProxyFunc(nil)
// ...
```

**Comment by Wangzhijie2016** [comment]
Ok i try it, thanks
