### ISSUE TITLE
Unable to set the Host header

### ISSUE THREAD

**Issue by ericraio** [gocolly/colly#564]
When I log out `httputils.DumpRequest` in `http_backend.go`, I can see that the Host header was never set from the OnRequest callback.

For our project, we need to set the Host header on each visit, diving into the code, it seems like that's not possible unless I am mistaken. Any solutions or should I submit a pull request?

**Comment by hakluke** [comment]
Hey @ericraio - I'm also trying to resolve this, did you find a solution?

**Comment by WGH-** [comment]
Wasn't this fixed by 9a56fbe6c0e6633629b1483a3a215b5c38ac1b5f?
