### ISSUE TITLE
Out-of-date version of xmlquery introduces security vulnerability

### ISSUE THREAD

**Issue by lamados** [gocolly/colly#581]
This package currently uses `xmlquery` v1.2.4 which is affected by a high-severity vulnerability (as described [here](https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMANTCHFXXMLQUERY-608944)). This was talked about in [this issue](https://github.com/antchfx/xmlquery/issues/39) and is no longer present in v1.3.1 and above, so `colly` should probably be updated to use the latest version (v1.3.3).

**Comment by asciimoo** [comment]
Fixed in #582, thanks!
