### ISSUE TITLE
goroutine memory leaks

### ISSUE THREAD

**Issue by maybgit** [gocolly/colly#584]
colly  v1.2.0

c.Limit(&colly.LimitRule{DomainGlob: "*", Parallelism: 20})
When parallelism is turned on, goroutine memory leaks

// c.Limit(&colly.LimitRule{DomainGlob: "*", Parallelism: 20})
Note that this line is normal

**Comment by asciimoo** [comment]
Please provide more information to help us in debugging

**Comment by lorentz-wu** [comment]
goroutine profile: total 199667
199503 @ 0x43cce5 0x4074ba 0x407215 0xdffb5e 0xdfed2a 0xdf74e5 0x473501
#	0xdffb5d	github.com/gocolly/colly/v2.(*httpBackend).Do+0x75d	/home/lixian/go/pkg/mod/github.com/gocolly/colly/v2@v2.0.1/http_backend.go:170
#	0xdfed29	github.com/gocolly/colly/v2.(*httpBackend).Cache+0x69	/home/lixian/go/pkg/mod/github.com/gocolly/colly/v2@v2.0.1/http_backend.go:132
#	0xdf74e4	github.com/gocolly/colly/v2.(*Collector).fetch+0x244	/home/lixian/go/pkg/mod/github.com/gocolly/colly/v2@v2.0.1/colly.go:617

**Comment by lorentz-wu** [comment]
all goroutine block at   r.waitChan <- true

**Comment by WGH-** [comment]
This might be rate limiting simply working as intended.
