### ISSUE TITLE
colly.HTMLElement.Attr() cannot fetch data-* 

### ISSUE THREAD

**Issue by alive1944** [gocolly/colly#597]
I filtered a html tag, and I want to get the value of the data-* attribute of tag, like `<div data-tmp="a=1&b=2">...</div>`

I tried `ele.Attr("data-tmp")`, `ele.Attr("data")`, `ele.Attr("dataTmp")` but all failed. I find the document but didn't found out something

**Comment by asciimoo** [comment]
The first one should work. Are you sure that these `data-tmp` attributes are in the source code of the HTML document and it isn't generated by JS?

**Comment by alive1944** [comment]
sorry, my fault, I checked the html, it did not at first, it generated by js
