### ISSUE TITLE
Provide request with cookie example

### ISSUE THREAD

**Issue by ev33ny** [gocolly/colly#599]
Hello!
Can you explain to me how to send a request with my custom cookie?
I try to set cookie like this, but this not working.
```
  mainCollector.Limit(&colly.LimitRule{DomainGlob: "*", Parallelism: parallelism})
  cookie := http.Cookie{
    Name:  "region_id",
    Value: "2",
    Path:  "/",
  }
  var cookies []*http.Cookie
  cookies = append(cookies, &cookie)
  mainCollector.SetCookies("*", cookies)
 ```

I'm new with Go and maybe I'm doing something wrong. I would be grateful for a detailed answer.
Thanks!

**Comment by WGH-** [comment]
I don't think match-all wildcards like this work for cookies. If you really want to send the same cookie for all domains, I think you should better use custom `Cookie` header, see `Collector`'s `Request` method.
