### ISSUE TITLE
How to scrape HTML string?

### ISSUE THREAD

**Issue by davioooh** [gocolly/colly#601]
Is it possible to use Colly to scrape HTML strings? I mean, I'd like to directly provide a string to the Collector, without executing an HTTP request.

Browsing the project docs I can't find this feature... Is there a way to achieve this?

Thanks!

**Comment by WGH-** [comment]
There's no way at the moment.

What's your use case, anyway?

**Comment by davioooh** [comment]
@WGH- thanks.

I have some HTML documents stored as text in my application DB and I'd like to parse and extract data from them.

**Comment by WGH-** [comment]
Not sure why you need Colly for that, since you can use e.g. github.com/PuerkitoBio/goquery directly.

**Comment by davioooh** [comment]
@WGH- I didn't know goquery project. Thank you very much for your suggestion.
