### ISSUE TITLE
Can Colly Access Window Object?

### ISSUE THREAD

**Issue by ariefsn** [gocolly/colly#606]
Hi, have a question.
I need to access some data from window object. eg window['customData']
Can Colly do that?

Thanks

**Comment by WGH-** [comment]
No. Colly doesn't execute JavaScript.

**Comment by ariefsn** [comment]
Hi @WGH- 
so what if need to wait for some sec?
eg:
`<div class="stats">0</div>`
but after some seconds, it'll become
`<div class="stats">7</div>`

I always get 0 value,
any idea to handle that?

Thanks
