### ISSUE TITLE
Get Element Value After Some Seconds

### ISSUE THREAD

**Issue by ariefsn** [gocolly/colly#607]
Hi,
There's case like this, the value of element needs some seconds to change. This is triggered by JS.
Any suggestion how to do that?

eg:
`<div class="stats">0</div>`
but after some seconds, it'll become
`<div class="stats">7</div>`

I always get 0 value,
any idea to handle that?

Thanks

**Comment by WGH-** [comment]
The answer is the same: Colly doesn't execute JavaScript.

**Comment by WGH-** [comment]
You might want to look at the browser's Network activity tab to see what requests load this data. Maybe you could do these AJAX calls directly.
