### ISSUE TITLE
How does colly set up web authentication , Such as NTLM, BASIC and Digest-MD5

### ISSUE THREAD

**Issue by baerwang** [gocolly/colly#613]

**Comment by WGH-** [comment]
It doesn't.

If you want to implement this, I think the way to do this is to provide custom `http.RoundTripper` that handles this.

**Comment by WGH-** [comment]
There seems to be plenty of packages providing custom `http.RoundTripper` (obviously I'm unsure of their quality):  https://github.com/vadimi/go-http-ntlm  https://github.com/Azure/go-ntlmssp https://github.com/rkl-/digest

As of Basic auth, it's even simpler: just call `r.SetBasicAuth` in Colly's `OnRequest` handler.
