### ISSUE TITLE
how to get the body of post request in onError or onResponse or onHtml ?

### ISSUE THREAD

**Issue by alive1944** [gocolly/colly#617]
```
c.OnResponse(func(r *colly.Response) {
		d, _ := ioutil.ReadAll(r.Request.Body)
		fmt.Println("---", string(d))
}

c.Post(url, reqData)
```

I used this to try to read the request data,but got empty string, an I didn't found there is other way to get the post data

**Comment by WGH-** [comment]
`r.Request.Body` is already read by the HTTP client at that point, and cannot be read again. You'll have to find another way to work around this, perhaps by stashing it inside context.
