### ISSUE TITLE
Wait on website before end visiting to load all the data

### ISSUE THREAD

**Issue by plussoftjo** [gocolly/colly#622]
Hello.
Thank you for this great work I love it very much.

I try it in a lot of website its work fine.

but I have problem with website its have load full then have request on it to display data.
the colly its finish visit before the data display and get the html empty.

its have any option to keep the colly in the page before end visiting to get all the data ?

**Comment by WGH-** [comment]
I assume the page loads extra data with JavaScript, which Colly doesn't execute at all.
