### ISSUE TITLE
Colly documentation website (http://go-colly.org/) is down

### ISSUE THREAD

**Issue by KakarN** [gocolly/colly#624]
Hi,

I have been trying to access the [go-colly](http://go-colly.org/) for days to find the documentation, but it is still unreachable. Could you tell me if there is any other way to access the documentation?

**Comment by certifiedloud** [comment]
@KakarN Maybe not as good as the docs on the website, but you can use this for reference:
https://pkg.go.dev/github.com/gocolly/colly/v2

**Comment by KakarN** [comment]
@certifiedloud  Thanks. Also, the website is live again!
