### ISSUE TITLE
Limit (or get) number of active requests

### ISSUE THREAD

**Issue by vryazanov** [gocolly/colly#648]
Hi there,
In my case I have 500k urls that i'm going to crawl with gocolly. Is there a way to limit number of active goroutines somehow? I call `.Visit` method 500k time and as a results I have the same number of goroutines and after that my service runs out of memory.
I was thinkig about doing something like that:
```golang
	activeRequests := make(chan struct{}, 128)

	collector := colly.NewCollector(colly.Async(true))
	collector.OnScraped(func(r *colly.Response) {
		<-activeRequests
	})
	for _, url := range urls {
		activeRequests <- struct{}{}
		collector.Visit(url)
	}

	collector.Wait()
```
This works more or less fine, but in some cases`.fetch` method exits without even calling `handleOnError`, so as you understands at some moment the code just freezes.

Is there a clean way to handle it? Thanks in advance.

**Comment by WGH-** [comment]
I think queue (`github.com/gocolly/colly/v2/queue`) is supposed to help in scenarios like this.

> This works more or less fine, but in some cases.fetch method exits without even calling `handleOnError`, so as you understands at some moment the code just freezes.

However, it doesn't look like you're actually limiting the number of concurrently running goroutines here. You're limiting the number of concurrent requests. If it actually solves the problem, you might want to look into `c.Limit` to limit concurrency in a more fail-proof way.
