### ISSUE TITLE
I have a problem with turkish characters when i use colly for search in golang

### ISSUE THREAD

**Issue by Sinanaltundag** [gocolly/colly#654]
when i use golang / colly for visit search pages of some web sites, I can not get all results if I use turkish characters like "ş,ç,ü".

example 1 =>

c.Visit(https://www.***.com/ara?q=g%C3%BCm%C3%BC%C5%9Fl%C3%BCk+cam)
// approximately 70 search results (it changes -+5 for each run?)

example 2 =>

c.Visit(https://www.***.com/ara?q=gümüşlük+cam)
// 0 search result

but when I search with web explorer, I can find 110 search results. there is not any problem without turkish characters, results are same. what can I do?

**Comment by WGH-** [comment]
You should urlencode the query yourself, as colly doesn't do that automatically right now (but I personally think it should - #596). Browsers do, that's why it works there.
