### ISSUE TITLE
HTTPS Proxy support

### ISSUE THREAD

**Issue by edoardottt** [gocolly/colly#661]
Is there HTTPS support for the proxy in the roadmap?

**Comment by WGH-** [comment]
Although the doc says otherwise (it only mentions `http` and `socks5`), `https` should also work, since proxy support is provided by stdlib `net/http.Transport`, which supports HTTPS since Go 1.10.

**Comment by edoardottt** [comment]
Thank you for the answer, maybe I'm doing something wrong.. But I can't understand why with the Burpsuite proxy I can't send requests using HTTPS protocol. And moreover I can't find a solution, even if burpsuite with its browser works fine

**Comment by WGH-** [comment]
Unless they changed it recently, I'm pretty sure Burp is HTTP proxy.

> But I can't understand why with the Burpsuite proxy I can't send requests using HTTPS protocol. And moreover I can't find a solution, even if burpsuite with its browser works fine

You can try harder. Or perhaps at least give any logs and more details about your setup.

**Comment by edoardottt** [comment]
My mistake, sorry. I was trusting the Burpsuite certificate only in the browser but not in my entire machine.  
I drop here a solution for whoever will encounter this problem. https://github.com/edoardottt/cariddi/wiki/BurpSuite-Integration
