### ISSUE TITLE
Recursively get other tags while visiting the next page

### ISSUE THREAD

**Issue by snoopysecurity** [gocolly/colly#674]
Hi, i have the below code where once I visit a page, i get all `script src` tags and `img src` tags, and then visit the next link. However, I see that from the next link onwards, colly doesn't get any img or script tags, is this expected? I assume I am doing something wrong

```
	c.OnHTML(`body`, func(e *colly.HTMLElement) {
		imgTags := e.ChildAttrs(`img`, "src")
		scriptSrc := e.ChildAttrs(`script`, "src")

		for _, href := range imgTags {
			targetUrls = append(targetUrls, e.Request.AbsoluteURL(href))
		}
		for _, href := range scriptSrc {
			targetUrls = append(targetUrls, e.Request.AbsoluteURL(href))

		}

	})

	c.OnHTML("a[href]", func(e *colly.HTMLElement) {
		log.Println("Next page link found:", e.Attr("href"))
		e.Request.Visit(e.Request.AbsoluteURL(e.Attr("href")))
	})
```

**Comment by betazk** [comment]
the content ,response when fetch the next link ,contains any tags?

**Comment by snoopysecurity** [comment]
Yeah, but its fine, i ended going with a different library so i ll close this issue, thanks
