### ISSUE TITLE
async stop process

### ISSUE THREAD

**Issue by dfelici87** [gocolly/colly#688]
Hi,

I use colly with these config:
...
colly.Async(true)
...
_ = colly.Limit(&colly.LimitRule{DomainGlob: "*", Parallelism: 100})
...

How can i stop immediatly colly works when a certain condition happens?
for example when i visited 100 urls?

thanks a lot.

**Comment by amirrmonfared** [comment]
Hi,
You can abort all requests.

```
c.OnRequest(func(r *colly.Request) {
  if cond {
    r.Abort()
  }
})
```

Also this

```
func CrawlSite(urlSite string, saveto string, config CollyConfig) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("exit crawl")
		}
	}()
        c := cly.NewCollector()

	// SOME CODE

	c.OnResponse(func(r *cly.Response) {
                // SOME CODE
		if (elapsed > waitTime) || (downloaded >= config.MaxAmount) {
			panic("Exit")
		}
                // SOME CODE
	})
        // SOME CODE
	c.Visit(url)
}
```

**Comment by WGH-** [comment]
The proper solution is to use `StdlibContext` (there has not been a colly release, but it's in master branch).

**Comment by as882301** [comment]
> The proper solution is to use `StdlibContext` (there has not been a colly release, but it's in master branch).

When will it be released？
