### ISSUE TITLE
How to add http/2.0 headers to the OnRequest callback function

### ISSUE THREAD

**Issue by n1e** [gocolly/colly#690]
![image](https://user-images.githubusercontent.com/26928453/156875433-0147bf97-cb8e-425d-9b89-64379719c21a.png)

use r.Headers.add() directly,  will be prompted with "net/http: invalid header filed name..."

**Comment by WGH-** [comment]
I don't think it's exposed in Go `net/http` library.

What are you trying to accomplish, anyway? The `:path:` thing is set automatically from the URL, for example.
