### ISSUE TITLE
[question]how use http1.1 pipeline requests?

### ISSUE THREAD

**Issue by hktalent** [gocolly/colly#699]
I am now concurrently making all requests to a target site in a socket connection without closing the socket, thereby improving performance. Can you give me some advice?
Also I will make sure:
Connection: Keep-Alive
In other words, I want to achieve
http pipeline request
https://en.wikipedia.org/wiki/HTTP_pipelining

**Comment by WGH-** [comment]
I don't think Go `net/http` library supports request pipelining. You can use a customized transport instead of `net/http` that support pipelining (if that exists or if you write one), and that doesn't require modifying colly's code.
