### ISSUE TITLE
stop collector 

### ISSUE THREAD

**Issue by amirrmonfared** [gocolly/colly#701]
Hi, 

I have a program written with colly and I have an issue with how can I stop the collector, the site I scrapping will never end because have too much data and I need to stop the collector.

It's possible to stop by channels but if the program has this feature already or can we add this to the project it will be great.

**Comment by satvik007** [comment]
You can abort all requests.
```
c.OnRequest(func(r *colly.Request) {
  if cond {
    r.Abort()
  }
})
```

**Comment by satvik007** [comment]
[Also this](https://github.com/gocolly/colly/issues/109#issuecomment-506995291)
