### ISSUE TITLE
 A variable null pointer appears when running concurrently

### ISSUE THREAD

**Issue by 265525** [gocolly/colly#706]
![RLRKSC0 84F L3M}LJCS}PP](https://user-images.githubusercontent.com/30653455/170206725-58017e20-1681-4ece-8666-d4ba95bc2a84.png)
![VNVYADT(2SPF%9{1ZP 5 19](https://user-images.githubusercontent.com/30653455/170206735-668d295b-c5bc-423d-bd91-11cedeefc927.png)
![OS E`FHRRT847H%9 X34(5T](https://user-images.githubusercontent.com/30653455/170206749-081b3432-b589-4df4-ae66-ace6d0738c40.png)
![L8%@TZ0{PB4U}W1_Y~)MA(T](https://user-images.githubusercontent.com/30653455/170206761-5e4f0bed-0b9f-487f-9bee-603602cebdec.png)
It won't do this without adding the restriction code,I don't know why this happens, hope you can tell me why, thanks

**Comment by WGH-** [comment]
Please post some code that we can run, not partially blurred screenshots. You didn't even provide the error message pointing to where the nil pointer appears.

I will reopen if you give me more info, and the issue is actually valid.
