### ISSUE TITLE
map data is lost on post request

### ISSUE THREAD

**Issue by 265525** [gocolly/colly#707]
When I colly.Post(url,map[string]string{"pwd":"admin","user":"admin","_token":""}) the _pwd in map[string]string will be lost , what is the situation, in the case of single thread and multi-thread, I suspect this is a bug
![GF9$Z}F 1WZ86QN5O0{_K96](https://user-images.githubusercontent.com/30653455/170407571-945a1b0e-8dcb-4dc9-a308-6fa4d62fc79c.png)

![QA7}~B %2{N{P9T8@`PKPBT](https://user-images.githubusercontent.com/30653455/170407511-800b58da-6751-4963-b133-9948836f2fc1.png)
![`)EDJ`JHMY8)_V79J1TS1~L](https://user-images.githubusercontent.com/30653455/170407517-3b4b775b-cb07-46e1-a974-e200a0772a78.png)
![EM19PWF~3)A90SD5J $OBK](https://user-images.githubusercontent.com/30653455/170407525-3f7cead5-8205-4247-a018-46b48ca90df9.png)

**Comment by WGH-** [comment]
Please provide an reproducible example, not a screenshot of a part of your program.
