### ISSUE TITLE
Scrap data that fill with JS

### ISSUE THREAD

**Issue by amirrmonfared** [gocolly/colly#719]
Hi, I'm trying to scrap [this site](https://www.navasan.net/). the data is commonly changing with JS. How can I access them?

sample path: #Ctable1 > div:nth-child(4) > table > tbody > tr:nth-child(1) > td.price

The code:
`func Scraper(URL string) error {

	// Instantiate default collector
	collector := colly.NewCollector()

	collector.OnHTML(".table.table-striped.table-hover tr", func(e *colly.HTMLElement) {
		currencies := Currency{
			code: e.ChildText("th a"),
			price: e.ChildText("td:first-of-type"),
		}
		fmt.Println(currencies)
		//ListOfCurrencies = append(ListOfCurrencies, currencies)
	})

	collector.OnRequest(func(r *colly.Request) {
		fmt.Println("visiting", r.URL)
	})

	collector.Visit(URL)

	return nil
}`

**Comment by TJSeabury** [comment]
As far as I know, Colly is not capable of JS execution. I would recommend you use [Puppeteer](https://pptr.dev/), a headless browser, as it can load and execute the JS on the page.
