### ISSUE TITLE
backend cache does not work.

### ISSUE THREAD

**Issue by godcong** [gocolly/colly#724]
1. I have set `CacheDir`.
2. When I use visit for the first time, the return value is normal
3. When I visit the same address for the second time, no value is returned.

I debugged colly's code and found that `requestCheck` was returning the error `ErrAlreadyVisited` on the second request, even though I had cached the request.

**Comment by satvik007** [comment]
```
// AllowURLRevisit instructs the Collector to allow multiple downloads of the same URL
func AllowURLRevisit() CollectorOption {
	return func(c *Collector) {
		c.AllowURLRevisit = true
	}
}
```

You need to set this to true if you want colly to revisit the url.
Set it like this.

```
colly := colly2.NewCollector(colly2.AllowURLRevisit())
```

**Comment by godcong** [comment]
@satvik007 thanks
