### ISSUE TITLE
Intall gocolly on raspberry - raspbian

### ISSUE THREAD

**Issue by gilles0606** [gocolly/colly#726]
Hello,

on Raspberry

root@raspberrypi:~# go get github.com/gocolly/colly/...
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

A try this

go install  github.com/gocolly/colly@latest
---
package github.com/gocolly/colly is not a main package

do you have an idea ?

Thanks

**Comment by Yuno-obsessed** [comment]
Dunno if it's yet an active question, but you definitely should read about how to manage ***go packages***
I recommend you to go through [this tutorial](https://go.dev/doc/tutorial/getting-started).
In your issue, you just trying to install colly package *when you aren't in directory with go.mod file*.
##### So basically create a directory
> mkdir first_scrapper
##### Create a new go file
> touch main.go
##### Inititalize your file as go package
> go mod init first_scrapper
And  then install gocolly
> go get github.com/gocolly/colly
After this you can use gocolly in your go project. :fire:

**Comment by tsafs** [comment]
I just downgraded to go 1.14 and was able to install v2.1.0 with `go get github.com/gocolly/colly/v2/...`

**Comment by WGH-** [comment]
All of this has nothing to do with Raspberry Pi.

To use colly, run `go get github.com/gocolly/colly/v2@latest` inside your Go module.
