### ISSUE TITLE
Support default callbacks

### ISSUE THREAD

**Issue by mortymacs** [gocolly/colly#729]
Hi,

In some situations in our project, we need to have some default callbacks like `OnRequest` to append default headers and cookie, and default `OnResponse` to do some specific logic in all scenarios, and so on.

So, in the whole process I have to call `.NewCollection()` call `.Clone()` methods and add those default callbacks. So, I was thinking maybe it's a good idea to support default callback in the framework level.

I didn't find this feature in Colly and I'm ready to implement it and send the PR if you approve the idea :)

Cheers,
Mort

**Comment by atkrad** [comment]
This feature is very useful and needed. When it will be approved?

**Comment by mortymacs** [comment]
No news?

**Comment by allcapsc** [comment]
Would appreciate this!

**Comment by p-afraz** [comment]
This is really needed by us, too! Would appreciate if you merge it.

**Comment by WGH-** [comment]
Default on what level? Global callbacks for all collectors? I'm strongly against this idea.

**Comment by mortymacs** [comment]
> Default on what level? Global callbacks for all collectors? I'm strongly against this idea.

Sorry I've forgotten to respond. It's not a global callback. It's default callbacks for a new collector.

The real case, for example:
1. `GET` base URL (`OnHTML` for parsing response, `OnRequest` to add custom headers, `OnError` for loging errors)
1.1. Parse form elements names
1.2. Update those elements by new value
2. `POST` the form (`OnHTML` for parsing response body and headers)
3. `GET` respond path (`OnHTML` for parsing response and find a value there)
4. ...

So, in this simple flow, we have 5 registered callbacks. In the last 2 `OnHTML` callbacks, we have problem because we have to remove previous `OnHTML` callbacks to not interfere our responses. We call `.Clone` but now we missed `OnRequest` and `OnError` callbacks. Now, we have to register them again. Now, consider the project is big and we have many flows, then we have to define some functions to do that for us and calling them again and again.

**Comment by mortymacs** [comment]
Nobody from the community is interested in the idea. So, I closed the issue.
