### ISSUE TITLE
How long does colly's cache last?

### ISSUE THREAD

**Issue by Caixetadev** [gocolly/colly#752]
I'm making an application and I'm using colly's cache but I don't know how long it takes for colly's cache to expire and I couldn't find a way to set the maximum time for the cache.

**Comment by blagoySimandov** [comment]
I don't exactly understand the question. Colly creates a folder in the place you tell it to (with colly.CacheDir("./_cachefoldername_")), where it collects all the visited pages. That way, if a page gets visited for a second time, Colly can check the cache and see that it shouldn't crawl it. The cache will not get deleted automatically by Colly even after the crawling is finished unless some external action does so (like the user manually doing so). That means you can start a crawler, stop it midway, and start it again after a while and still be sure that every page will be crawled only once. Hope this helped.

**Comment by Caixetadev** [comment]
yes it helped, thx
