### ISSUE TITLE
Suggestion: Functional options for NewCollector

### ISSUE THREAD

**Issue by peterhellberg** [gocolly/colly#80]
Implementing [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) for the `NewCollector` constructor function would allow the user to setup the collector without manually setting field values on `*Collector`

> This would be a non breaking change since the options would be a variadic argument to `NewCollector`

Examples of options could be to add a domain to the `AllowedDomains` field: `NewCollector(AllowDomain("example.com"))` 

What do you think?

**Comment by peterhellberg** [comment]
If this would be something you like than I can open a PR.

**Comment by asciimoo** [comment]
@peterhellberg thank you for your suggestion, this is an interesting idea (and a good article), I really like it. It would make the API cleaner without breaking compatibility.
I'd appreciate it if you could work on this. Thanks in advance.

**Comment by peterhellberg** [comment]
Ok.

I'll probably have some time this weekend to work on this.
