### ISSUE TITLE
Suggestion: Use httptest instead of manually running HTTP server

### ISSUE THREAD

**Issue by peterhellberg** [gocolly/colly#83]
Currently there is code in the tests [manually running a HTTP server](https://github.com/gocolly/colly/blob/d88ceb06fe7bdb82d531d4caf87b6bd91e4dfe65/colly_test.go#L15-L105) to run test against, this is what the [net/http/httptest](https://golang.org/pkg/net/http/httptest/) package is meant to be used for.

**Comment by asciimoo** [comment]
You're right, it would be a better solution. Would you like to work on this?

**Comment by peterhellberg** [comment]
Yes, I've used `*httptest.Server` in a few projects before so there shouldn't be any surprises…

I can take a look at making this change later, but first I'm going to visit my grandmother 😃

**Comment by asciimoo** [comment]
Implemented: 132289a
Thank you!
