### ISSUE TITLE
Extend basic example with more callbacks

### ISSUE THREAD

**Issue by rongyi** [gocolly/colly#90]
There are five main callbacks in colly and they are:
1. OnRequest
2. OnError
3. OnResponse
4. OnHTML
5. OnScraped

We want to show reader these callbacks at the very beginning, so how about we extend the basic example with all those callbacks?

**Comment by asciimoo** [comment]
@rongyi There is no intent to extend the basic example with all the supported features. We have a dedicated documentation section which describes all the callbacks: http://go-colly.org/docs/introduction/start/#callbacks. What about adding a comment with this link to the basic example?

**Comment by rongyi** [comment]
Wow! Colly doc is great, I would not open this issue if I saw the page. I read your code to get all these callbacks, there's no need to duplicate this. It would be better if you add a doc link in README, so reader can just jump to doc.
