### ISSUE TITLE
very high memory usage

### ISSUE THREAD

**Issue by alltheoptions** [gocolly/colly#92]
I am running on windows 10 [paraller example](https://github.com/gocolly/colly/blob/master/_examples/parallel/parallel.go), after a few minutes this is what happens:

![taskmgr_2018-01-17_18-52-20](https://user-images.githubusercontent.com/30186018/35058315-d69e6b82-fbb7-11e7-9da4-8b9fe1200be7.png)

**Comment by alltheoptions** [comment]
From what i know its my lack of understanding the language and code itself.
Maybe someone wants to explain why it does happen :)

**Comment by asciimoo** [comment]
The peak memory usage of this script on my machine is `120376K` - reported by `time(1)` command under linux. What is your go version/system specs?

**Comment by alltheoptions** [comment]
Everything works fine now. I guess it was MY error somewhere.

**Comment by alltheoptions** [comment]
Yes, everything works fine now... i guess the error wason ME.
Sorry
