### ISSUE TITLE
#question -> is there an easy way to limit queue?

### ISSUE THREAD

**Issue by alltheoptions** [gocolly/colly#93]
While using [parallel ](https://github.com/gocolly/colly/blob/master/_examples/parallel/parallel.go) memory is growing forever. Is there an **easy** approach that you can think of to limit queue that holds urls to visit?

**Comment by asciimoo** [comment]
@alltheoptions use `LimitRule` to define queue limits:
 - https://godoc.org/github.com/gocolly/colly#LimitRule
 - https://godoc.org/github.com/gocolly/colly#Collector.Limit

**Comment by alltheoptions** [comment]
@asciimoo thanks for answer, from my understanding there is no built-in queue limit, you mean that i should implement my own?

**Comment by asciimoo** [comment]
@alltheoptions `LimitRule` is the built-in queue limit, here's an example how to use it: http://go-colly.org/docs/examples/rate_limit/
