### ISSUE TITLE
URL Filter to exclude

### ISSUE THREAD

**Issue by cameronbraid** [gocolly/colly#94]
Currently you can specify a URLFIlter to include URL, is there any way to exclude urls ?

**Comment by asciimoo** [comment]
The trivial answer would be the [negative look ahead](https://www.regular-expressions.info/lookaround.html) regular expression feature, but it isn't supported by Golang. There is a workaround mentioned in the first answer of this stackoverflow question: https://stackoverflow.com/questions/26771592/negative-look-ahead-go-regular-expressions .
As an other option, you can create an OnRequest callback which cancels the request:
```go
c.OnRequest(func(r *colly.Request) {
	if r.URL.Host == "unwantedhost.com" {
		r.Abort()
	}
})
```
`Request.Abort()` introduced in 44e13404eb54f3abfd28007d360c4bb5ef6fa9c3
